import { createContext, useContext, useState, useEffect } from "react";

const AccessibilityContext = createContext(null);

const translations = {
  en: {
    home: "Home",
    reportAbuse: "Report Abuse",
    login: "Login",
    logout: "Logout",
    cases: "Cases",
    analytics: "Analytics",
    admin: "Admin",
    heroTitle: "Protecting Children Online",
    heroSubtitle: "Mlinzi helps children in Rwanda report online abuse and get support safely and anonymously.",
    reportNow: "Report Abuse",
    howItWorks: "How It Works",
    step1Title: "Upload",
    step1Desc: "Take a screenshot of the harmful message",
    step2Title: "Analyze",
    step2Desc: "Our AI checks if it is harmful",
    step3Title: "Protect",
    step3Desc: "Get advice and connect to help",
    safetyMessage: "Your safety comes first. You are not alone.",
    analysisResults: "Analysis Results",
    riskLevel: "Risk Level",
    confidence: "Confidence",
    category: "Category",
    whatToDo: "What You Should Do",
    extractedText: "Extracted Text",
    counselorHelp: "Would you like help from a trained child protection counselor?",
    stayAnonymous: "Keep this anonymous",
    connectCounselor: "Connect me to a counselor",
    connectWithCounselor: "Connect with a Counselor",
    reportAnother: "Report Another",
    backToHome: "Back to Home",
    thankYou: "Thank you for speaking up. Your report helps protect other children too.",
    district: "District",
    selectDistrict: "Select your district",
    preferredContact: "Preferred contact method",
    phoneCall: "Phone call",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "Email",
    bestTime: "Best time to contact",
    bestTimePlaceholder: "e.g., Morning, After school, Anytime",
    areYouSafe: "Are you currently safe?",
    submitReferral: "Submit Referral",
    contactEncrypted: "Your contact information is encrypted and only shared with your assigned counselor.",
    counselorDashboard: "Counselor Dashboard",
    manageReferrals: "Manage referrals and support children in need",
    myCases: "My Cases",
    unclaimed: "Unclaimed",
    newCases: "New Cases",
    inReview: "In Review",
    allStatuses: "All Statuses",
    new: "New",
    underReview: "Under Review",
    resolved: "Resolved",
    refresh: "Refresh",
    loadingCases: "Loading cases...",
    noCases: "No cases found",
    noMyCases: "You don't have any assigned cases yet.",
    noUnclaimed: "All cases have been claimed.",
    claim: "Claim",
    viewDetails: "View Details",
    nationalDashboard: "National Dashboard",
    evidenceInsights: "Evidence-driven insights for policy and decision makers",
    totalReports: "Total Reports Submitted",
    escalatedToCounselors: "escalated to counselors",
    highSeverity: "High Severity",
    referrals: "Referrals",
    avgResponse: "Avg Response",
    bySeverity: "By Severity",
    noDataYet: "No data yet",
    byCategory: "By Category",
    byDistrict: "By District",
    byChannel: "By Channel",
    responseTimeByDistrict: "Response Time by District",
    noResponseData: "No response time data yet",
    casesLabel: "cases",
    referralStatus: "Referral Status",
    noReferrals: "No referrals yet",
    monthlyTrend: "Monthly Trend",
    dataSummary: "Data Summary",
    dataSummaryText: "This dashboard provides an overview of all reports submitted through Mlinzi. Data is updated in real-time as new reports are received. All data is anonymous and aggregated to protect children's privacy. Use these insights to inform policy decisions and allocate resources where they are needed most.",
    safetyAdvice: "SAFETY ADVICE",
    safetyTip1: "Do not reply to the harmful message",
    safetyTip2: "Block the person sending it",
    safetyTip3: "Take a screenshot as evidence",
    safetyTip4: "Tell a trusted adult",
    safetyTip5: "You are not alone - help is available",
    accessibility: "Accessibility",
    highContrast: "High Contrast",
    largeText: "Large Text",
    language: "Language",
    reportDescription: "Tell us what happened. Your report can remain anonymous.",
    dropScreenshot: "Drop your screenshot here",
    typeInstead: "Type the message instead",
    analyzing: "Analyzing your screenshot...",
    uploadAnalyze: "Upload & Analyze",
    lowRisk: "Low Risk",
    lowRiskMsg: "This message appears to be safe. You are doing great!",
    mediumRisk: "Medium Risk",
    mediumRiskMsg: "This message may need attention. Let's protect you together.",
    highRisk: "High Risk",
    highRiskMsg: "This message may be unsafe. Let's protect you together.",
    analyzingReport: "Analyzing...",
    aiReviewing: "Our AI is reviewing your report.",
    actionGuidanceOnly: "Safety Guidance",
    actionGuidanceOnlyDesc: "Follow the safety advice below",
    actionAnonymousReport: "Anonymous Report",
    actionAnonymousReportDesc: "This has been logged for national statistics",
    actionConnectCounselor: "Counselor Support",
    actionConnectCounselorDesc: "We recommend connecting with a counselor",
    actionEmergencyReferral: "Emergency",
    actionEmergencyReferralDesc: "Please seek immediate help",
    noReportData: "No report data found",
    uploadToStart: "Upload a screenshot to get started.",
    aiReviewedMsg: "Our AI has reviewed the message. Here is what we found.",
    mlinziAnalysis: "Mlinzi AI Analysis",
    whatFoundInMessage: "What we found in the message",
    wouldLikeHelp: "Would you like help from a trained child protection counselor?",
    stayAnonymousOrConnect: "You can stay anonymous or connect with someone who can help.",
    keepAnonymous: "Keep this anonymous",
    connectMeCounselor: "Connect me to a counselor",
    selectYourDistrict: "Select your district",
    contactMethod: "Preferred contact method",
    phoneWhatsappNumber: "Phone/WhatsApp number",
    submitting: "Submitting...",
    contactEncryptedNote: "Your contact information is encrypted and only shared with your assigned counselor.",
    imageFileError: "Please upload an image file (jpg, png, gif, webp).",
    fileSizeError: "File must be under 5MB.",
    selectScreenshotOrType: "Please select a screenshot or type the message.",
    somethingWrong: "Something went wrong. Please try again.",
    clickOrDropReplace: "Click or drop to replace",
    orClickBrowse: "or click to browse, or paste from clipboard (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — max 5MB",
    typePasteHarmful: "Type or paste the harmful message here...",
    typeMessageDirectly: "You can type the message directly if the screenshot doesn't work.",
    anonymousNoData: "100% anonymous — no personal data collected",
    rightThing: "You did the right thing by asking for help.",
    aiWillAnalyze: "Our AI will analyze the message and provide clear guidance on what to do next. You are safe here.",
    counselDashboardSubtitle: "Manage referrals and support children in need",
    loadingAnalytics: "Loading analytics...",
    unableToLoad: "Unable to load analytics",
    tryRefreshing: "Please try refreshing the page.",
    evidenceDesc: "Evidence-driven insights for policy and decision makers",
    escalatedCounselors: "escalated to counselors",
    loadingCase: "Loading case...",
    caseNotFound: "Case not found",
    backToDashboard: "Back to Dashboard",
    caseNumber: "Case #",
    reportDetails: "Report Details",
    severity: "Severity",
    recommended: "Recommended",
    aiGuidance: "AI Guidance",
    screenshot: "Screenshot",
    followUpNotes: "Follow-up Notes",
    addNotePlaceholder: "Add a note about this case...",
    adding: "Adding...",
    addNote: "Add Note",
    noNotesYet: "No notes yet",
    contactInformation: "Contact Information",
    preferredContactLabel: "Preferred Contact",
    contactDetails: "Contact Details",
    currentlySafe: "Currently Safe?",
    timeline: "Timeline",
    submitted: "Submitted",
    aiAnalyzed: "AI Analyzed",
    counselorAssigned: "Counselor Assigned",
    firstResponse: "First Response",
    underReviewTimeline: "Under Review",
    resolvedTimeline: "Resolved",
    guidanceOnly: "Guidance Only",
    anonymousReportLabel: "Anonymous Report",
    connectToCounselor: "Connect to Counselor",
    emergencyReferralLabel: "Emergency Referral",
    problemSolving: "The Problem We're Solving",
    problemDesc: "Children across Africa face growing threats online, yet most lack safe ways to report abuse. Existing systems are slow, require personal data, and fail to reach children in rural communities.",
    ourPromise: "Our Promise to You",
    promise1: "Anonymous by default",
    promise1Desc: "No personal data required to get help",
    promise2: "AI-powered guidance",
    promise2Desc: "Instant analysis and safety advice",
    promise3: "Human support available",
    promise3Desc: "Connect with trained counselors when needed",
    promise4: "Multilingual",
    promise4Desc: "Available in English, French, and Kinyarwanda",
    everyChildProtected: "Every child. Everywhere. Protected.",
    builtForAfrica: "Mlinzi is built for children across Rwanda and Africa. Open-source, community-driven, and designed to scale to protect every child online.",
    aiPoweredPlatform: "AI-powered child digital protection platform",
    unicefProject: "Designed for UNICEF Rwanda & partners • Protect. Listen. Connect.",
    accessMlinzi: "Access Mlinzi Your Way",
    noSmartphone: "No smartphone? No internet? No problem...",
    webApp: "Web App",
    webAppDesc: "Upload screenshots and get instant AI analysis on any device with a browser.",
    smsDesc: "Text Mlinzi from any basic phone...",
    whatsappDesc: "Send messages, screenshots, and voice notes through WhatsApp...",
    oneInThree: "1 in 3",
    percent80: "80%",
    statChildren: "children",
    statReport: "never report abuse",
    statOnline: "of children in Africa",
    statOnlineDesc: "face online risks",
    statProtected: "protected",
    statProtectedDesc: "target — universal coverage",
    protect: "Protect",
    listen: "Listen",
    support: "Support",
    empower: "Empower",
    protectDesc: "AI-powered analysis",
    listenDesc: "Anonymous reporting",
    supportDesc: "Counselor connections",
    empowerDesc: "Child safety resources",
    unicefInnovation: "Designed for UNICEF Rwanda",
    videoNotSupported: "Your browser does not support the video tag.",
    cookieTitle: "Cookies & Privacy",
    cookieMessage: "We use essential cookies to keep Mlinzi running safely. We do not track you or share your data. By accepting, you help us improve child protection services across Africa.",
    cookieAccept: "Accept Cookies",
    cookieReject: "Reject",
    privacyTitle: "Privacy Policy",
    privacySubtitle: "How we protect children's data and privacy",
    privacyDataTitle: "1. What We Collect",
    privacyDataContent: "Mlinzi collects only what is needed to help children:\n\n• Screenshots or text messages reported by the child\n• AI analysis results (category, severity, guidance)\n• District (only if the child requests counselor support)\n• Contact information (only if the child chooses to connect with a counselor)\n\nWe do NOT collect: names, photos, IP addresses, device information, or any identifying data from anonymous reports.",
    privacyUseTitle: "2. How We Use Data",
    privacyUseContent: "Data is used solely to:\n\n• Analyze reported messages for child safety\n• Provide guidance to children on how to stay safe\n• Connect children with trained counselors when requested\n• Generate anonymous national statistics for child protection policy\n\nWe never sell, share, or use data for advertising or profiling.",
    privacyProtectTitle: "3. How We Protect Data",
    privacyProtectContent: "• All data is encrypted in transit (HTTPS) and at rest\n• Access is restricted to authorized counselors only\n• Rate limiting prevents abuse and automated attacks\n• No tracking cookies or analytics trackers\n• Open-source code — publicly auditable",
    privacyChildrenTitle: "4. Children's Privacy",
    privacyChildrenContent: "Mlinzi is designed specifically for children. We follow the highest standards of child data protection:\n\n• Anonymous by default — no personal data required to get help\n• No accounts needed for basic reporting\n• Parental consent is not required for anonymous reporting\n• Counselor access requires explicit child consent\n• We comply with Rwanda's data protection laws and UNICEF's principles on children's digital safety",
    privacyRetentionTitle: "5. Data Retention",
    privacyRetentionContent: "• Anonymous reports: retained for up to 2 years for national statistics\n• Counselor-linked cases: retained for up to 1 year after case resolution\n• SMS/WhatsApp sessions: deleted after 90 days of inactivity\n• Contact information: deleted immediately after counselor connection\n• Children can request deletion at any time",
    privacyDeleteTitle: "6. Data Deletion",
    privacyDeleteContent: "Children (or their guardians) can request full deletion of their data at any time by:\n\n• Emailing privacy@mlinzi.org\n• Messaging Mlinzi with 'DELETE MY DATA'\n• Asking their counselor to submit a deletion request\n\nAll data will be permanently deleted within 72 hours of verification.",
    privacyRightsTitle: "7. Your Rights",
    privacyRightsContent: "Every child has the right to:\n\n• Report anonymously without providing any personal data\n• Know what data has been collected about them\n• Request correction of any inaccurate data\n• Request full deletion of their data\n• Withdraw consent for counselor connection at any time\n• File a complaint if they believe their privacy has been violated",
    privacyContactTitle: "8. Contact Us",
    privacyContactContent: "For privacy questions, data requests, or complaints:\n\nEmail: privacy@mlinzi.org\nPhone: +250 788 123 456\nAddress: UNICEF Rwanda, KG 7 Ave, Kigali\n\nData Protection Officer: dpo@mlinzi.org",
    privacyLastUpdated: "Last updated: August 2026 • A proposed AI-powered child digital protection platform",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc: "Enter your email and we'll send you a reset link",
    backToLogin: "Back to Login",
    checkEmailTitle: "Check Your Email",
    checkEmailDesc: "We sent a password reset link to",
    noEmailCheck: "Didn't receive it? Check your spam folder or try again.",
    tryDifferentEmail: "Use a different email",
    resetYourPassword: "Reset Your Password",
    enterEmailBelow: "Enter your registered email address",
    emailAddress: "Email Address",
    sending: "Sending...",
    sendResetLink: "Send Reset Link",
    resetPasswordTitle: "Set New Password",
    resetPasswordDesc: "Choose a strong password for your account",
    invalidResetLink: "Invalid Reset Link",
    invalidResetLinkDesc: "This password reset link is invalid or has expired.",
    requestNewLink: "Request a New Link",
    setNewPassword: "Set New Password",
    mustBe8Chars: "Must be at least 8 characters",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordsNoMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 8 characters",
    resetting: "Resetting...",
    passwordResetSuccess: "Password Reset Successful",
    passwordResetSuccessDesc: "Your password has been updated. You can now log in with your new password.",
    goToLogin: "Go to Login",
    enterPhoneNumber: "Enter Your Phone Number",
    otpWillBeSent: "We'll send a verification code via SMS",
    phoneLabel: "Phone Number",
    sendCode: "Send Code",
    enterCode: "Enter Verification Code",
    codeSentTo: "Code sent to",
    verifying: "Verifying...",
    verifyCode: "Verify Code",
    resendIn: "Resend code in",
    resendCode: "Resend Code",
    phoneVerified: "Phone Verified",
    phoneVerifiedDesc: "Your phone number has been verified. You can now set a new password.",
    chooseHowToReset: "How Would You Like to Reset?",
    chooseChannelDesc: "Choose where to receive your verification code",
    smsOtp: "SMS Code",
    smsOtpDesc: "Receive a 6-digit code via text message",
    emailOtp: "Email Code",
    emailOtpDesc: "Receive a 6-digit code via email",
    enterEmailAddress: "Enter Your Email Address",
    verificationVerified: "Verified Successfully",
  },
  fr: {
    home: "Accueil",
    reportAbuse: "Signaler un abus",
    login: "Connexion",
    logout: "Déconnexion",
    cases: "Cas",
    analytics: "Analytique",
    admin: "Admin",
    heroTitle: "Protéger les enfants en ligne",
    heroSubtitle: "Mlinzi aide les enfants au Rwanda à signaler les abus en ligne et à obtenir un soutien en toute sécurité et anonymement.",
    reportNow: "Signaler un abus",
    howItWorks: "Comment ça marche",
    step1Title: "Télécharger",
    step1Desc: "Prenez une capture d'écran du message nocif",
    step2Title: "Analyser",
    step2Desc: "Notre IA vérifie si c'est nocif",
    step3Title: "Protéger",
    step3Desc: "Obtenez des conseils et connectez-vous à l'aide",
    safetyMessage: "Votre sécurité passe en premier. Vous n'êtes pas seul.",
    analysisResults: "Résultats de l'analyse",
    riskLevel: "Niveau de risque",
    confidence: "Confiance",
    category: "Catégorie",
    whatToDo: "Ce que vous devriez faire",
    extractedText: "Texte extrait",
    counselorHelp: "Aimeriez-vous de l'aide d'un conseiller en protection de l'enfance?",
    stayAnonymous: "Rester anonyme",
    connectCounselor: "Me connecter à un conseiller",
    connectWithCounselor: "Se connecter à un conseiller",
    reportAnother: "Signaler un autre",
    backToHome: "Retour à l'accueil",
    thankYou: "Merci de parler. Votre rapport aide à protéger d'autres enfants aussi.",
    district: "District",
    selectDistrict: "Sélectionnez votre district",
    preferredContact: "Méthode de contact préférée",
    phoneCall: "Appel téléphonique",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "E-mail",
    bestTime: "Meilleur moment pour vous contacter",
    bestTimePlaceholder: "ex., Matin, Après l'école, N'importe quand",
    areYouSafe: "Êtes-vous en sécurité actuellement?",
    submitReferral: "Soumettre le referral",
    contactEncrypted: "Vos informations de contact sont cryptées et partagées uniquement avec votre conseiller assigné.",
    counselorDashboard: "Tableau de bord du conseiller",
    manageReferrals: "Gérer les referrals et soutenir les enfants dans le besoin",
    myCases: "Mes cas",
    unclaimed: "Non réclamés",
    newCases: "Nouveaux cas",
    inReview: "En revue",
    allStatuses: "Tous les statuts",
    new: "Nouveau",
    underReview: "En revue",
    resolved: "Résolu",
    refresh: "Rafraîchir",
    loadingCases: "Chargement des cas...",
    noCases: "Aucun cas trouvé",
    noMyCases: "Vous n'avez pas encore de cas assignés.",
    noUnclaimed: "Tous les cas ont été réclamés.",
    claim: "Réclamer",
    viewDetails: "Voir les détails",
    nationalDashboard: "Tableau de bord national",
    evidenceInsights: "Aperçus fondés sur des preuves pour les décideurs politiques",
    totalReports: "Total des rapports soumis",
    escalatedToCounselors: "escaladés aux conseillers",
    highSeverity: "Haute gravité",
    referrals: "Referrals",
    avgResponse: "Temps de réponse moyen",
    bySeverity: "Par gravité",
    noDataYet: "Pas encore de données",
    byCategory: "Par catégorie",
    byDistrict: "Par district",
    byChannel: "Par canal",
    responseTimeByDistrict: "Temps de réponse par district",
    noResponseData: "Pas encore de données de réponse",
    casesLabel: "cas",
    referralStatus: "Statut des referrals",
    noReferrals: "Pas encore de referrals",
    monthlyTrend: "Tendance mensuelle",
    dataSummary: "Résumé des données",
    dataSummaryText: "Ce tableau de bord fournit un aperçu de tous les rapports soumis via Mlinzi. Les données sont mises à jour en temps réel. Toutes les données sont anonymes et agrégées pour protéger la vie privée des enfants.",
    safetyAdvice: "CONSEILS DE SÉCURITÉ",
    safetyTip1: "Ne répondez pas au message nocif",
    safetyTip2: "Bloquez la personne qui l'envoie",
    safetyTip3: "Prenez une capture d'écran comme preuve",
    safetyTip4: "Parlez-en à un adulte de confiance",
    safetyTip5: "Vous n'êtes pas seul - de l'aide est disponible",
    accessibility: "Accessibilité",
    highContrast: "Contraste élevé",
    largeText: "Grand texte",
    language: "Langue",
    reportDescription: "Dites-nous ce qui s'est passé. Votre rapport peut rester anonyme.",
    dropScreenshot: "Déposez votre capture d'écran ici",
    typeInstead: "Tapez le message à la place",
    analyzing: "Analyse de votre capture d'écran...",
    uploadAnalyze: "Télécharger et analyser",
    lowRisk: "Faible risque",
    lowRiskMsg: "Ce message semble sûr. Vous faites du bon travail!",
    mediumRisk: "Risque moyen",
    mediumRiskMsg: "Ce message peut nécessiter une attention. Protégeons-vous ensemble.",
    highRisk: "Risque élevé",
    highRiskMsg: "Ce message peut être dangereux. Protégeons-vous ensemble.",
    analyzingReport: "Analyse...",
    aiReviewing: "Notre IA examine votre rapport.",
    actionGuidanceOnly: "Conseils de sécurité",
    actionGuidanceOnlyDesc: "Suivez les conseils de sécurité ci-dessous",
    actionAnonymousReport: "Rapport anonyme",
    actionAnonymousReportDesc: "Cela a été enregistré pour les statistiques nationales",
    actionConnectCounselor: "Soutien du conseiller",
    actionConnectCounselorDesc: "Nous vous recommandons de vous connecter à un conseiller",
    actionEmergencyReferral: "Urgence",
    actionEmergencyReferralDesc: "Veuillez chercher une aide immédiate",
    noReportData: "Aucune donnée de rapport trouvée",
    uploadToStart: "Téléchargez une capture d'écran pour commencer.",
    aiReviewedMsg: "Notre IA a examiné le message. Voici ce que nous avons trouvé.",
    mlinziAnalysis: "Analyse IA Mlinzi",
    whatFoundInMessage: "Ce que nous avons trouvé dans le message",
    wouldLikeHelp: "Aimeriez-vous de l'aide d'un conseiller en protection de l'enfance?",
    stayAnonymousOrConnect: "Vous pouvez rester anonyme ou vous connecter avec quelqu'un qui peut aider.",
    keepAnonymous: "Rester anonyme",
    connectMeCounselor: "Me connecter à un conseiller",
    selectYourDistrict: "Sélectionnez votre district",
    contactMethod: "Méthode de contact préférée",
    phoneWhatsappNumber: "Numéro de téléphone/WhatsApp",
    submitting: "Soumission...",
    contactEncryptedNote: "Vos informations de contact sont cryptées et partagées uniquement avec votre conseiller assigné.",
    imageFileError: "Veuillez télécharger un fichier image (jpg, png, gif, webp).",
    fileSizeError: "Le fichier doit être inférieur à 5 Mo.",
    selectScreenshotOrType: "Veuillez sélectionner une capture d'écran ou taper le message.",
    somethingWrong: "Une erreur s'est produite. Veuillez réessayer.",
    clickOrDropReplace: "Cliquez ou déposez pour remplacer",
    orClickBrowse: "ou cliquez pour parcourir, ou collez du presse-papiers (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — max 5 Mo",
    typePasteHarmful: "Tapez ou collez le message nocif ici...",
    typeMessageDirectly: "Vous pouvez taper le message directement si la capture d'écran ne fonctionne pas.",
    anonymousNoData: "100% anonyme — aucune donnée personnelle collectée",
    rightThing: "Vous avez bien fait de demander de l'aide.",
    aiWillAnalyze: "Notre IA analysera le message et fournira des conseils clairs sur la suite. Vous êtes en sécurité ici.",
    counselDashboardSubtitle: "Gérer les referrals et soutenir les enfants dans le besoin",
    loadingAnalytics: "Chargement des analytiques...",
    unableToLoad: "Impossible de charger les analytiques",
    tryRefreshing: "Veuillez rafraîchir la page.",
    evidenceDesc: "Aperçus fondés sur des preuves pour les décideurs politiques",
    escalatedCounselors: "escaladés aux conseillers",
    loadingCase: "Chargement du cas...",
    caseNotFound: "Cas non trouvé",
    backToDashboard: "Retour au tableau de bord",
    caseNumber: "Cas #",
    reportDetails: "Détails du rapport",
    severity: "Gravité",
    recommended: "Recommandé",
    aiGuidance: "Conseils IA",
    screenshot: "Capture d'écran",
    followUpNotes: "Notes de suivi",
    addNotePlaceholder: "Ajoutez une note sur ce cas...",
    adding: "Ajout...",
    addNote: "Ajouter une note",
    noNotesYet: "Pas encore de notes",
    contactInformation: "Informations de contact",
    preferredContactLabel: "Contact préféré",
    contactDetails: "Détails du contact",
    currentlySafe: "En sécurité actuellement?",
    timeline: "Chronologie",
    submitted: "Soumis",
    aiAnalyzed: "Analysé par IA",
    counselorAssigned: "Conseiller assigné",
    firstResponse: "Première réponse",
    underReviewTimeline: "En revue",
    resolvedTimeline: "Résolu",
    guidanceOnly: "Conseils uniquement",
    anonymousReportLabel: "Rapport anonyme",
    connectToCounselor: "Se connecter à un conseiller",
    emergencyReferralLabel: "Referral d'urgence",
    problemSolving: "Le problème que nous résolvons",
    problemDesc: "Les enfants à travers l'Afrique font face à des menaces croissantes en ligne, mais la plupart n'ont pas de moyens sûrs de signaler les abus. Les systèmes existants sont lents, nécessitent des données personnelles et ne parviennent pas aux enfants des communautés rurales.",
    ourPromise: "Notre promesse pour vous",
    promise1: "Anonyme par défaut",
    promise1Desc: "Aucune donnée personnelle requise pour obtenir de l'aide",
    promise2: "Guidage propulsé par IA",
    promise2Desc: "Analyse instantanée et conseils de sécurité",
    promise3: "Soutien humain disponible",
    promise3Desc: "Connectez-vous avec des conseillers formés si nécessaire",
    promise4: "Multilingue",
    promise4Desc: "Disponible en anglais, français et kinyarwanda",
    everyChildProtected: "Chaque enfant. Partout. Protégé.",
    builtForAfrica: "Mlinzi est construit pour les enfants à travers le Rwanda et l'Afrique. Open-source, communautaire et conçu pour se développer pour protéger chaque enfant en ligne.",
    aiPoweredPlatform: "Plateforme de protection numérique de l'enfant propulsée par l'IA",
    unicefProject: "Conçu pour l'UNICEF Rwanda et ses partenaires • Protéger. Écouter. Connecter.",
    accessMlinzi: "Accédez à Mlinzi à votre façon",
    noSmartphone: "Pas de smartphone? Pas d'internet? Pas de problème...",
    webApp: "Application Web",
    webAppDesc: "Téléchargez des captures d'écran et obtenez une analyse IA instantanée sur n'importe quel appareil avec un navigateur.",
    smsDesc: "Envoyez un SMS à Mlinzi depuis n'importe quel téléphone...",
    whatsappDesc: "Envoyez des messages, des captures d'écran et des notes vocales via WhatsApp...",
    oneInThree: "1 sur 3",
    percent80: "80%",
    statChildren: "enfants",
    statReport: "ne signalent jamais les abus",
    statOnline: "des enfants en Afrique",
    statOnlineDesc: "font face à des risques en ligne",
    statProtected: "protégés",
    statProtectedDesc: "cible — couverture universelle",
    protect: "Protéger",
    listen: "Écouter",
    support: "Soutenir",
    empower: "Autonomiser",
    protectDesc: "Analyse propulsée par l'IA",
    listenDesc: "Signalement anonyme",
    supportDesc: "Connexions avec des conseillers",
    empowerDesc: "Ressources de sécurité des enfants",
    unicefInnovation: "Conçu pour l'UNICEF Rwanda",
    videoNotSupported: "Votre navigateur ne prend pas en charge la balise vidéo.",
    cookieTitle: "Cookies et confidentialité",
    cookieMessage: "Nous utilisons des cookies essentiels pour garder Mlinzi en fonctionnement en toute sécurité. Nous ne vous suivons pas et ne partageons pas vos données. En acceptant, vous nous aidez à améliorer les services de protection de l'enfance en Afrique.",
    cookieAccept: "Accepter les cookies",
    cookieReject: "Refuser",
    privacyTitle: "Politique de confidentialité",
    privacySubtitle: "Comment nous protégeons les données et la vie privée des enfants",
    privacyDataTitle: "1. Ce que nous collectons",
    privacyDataContent: "Mlinzi ne collecte que ce qui est nécessaire pour aider les enfants :\n\n• Captures d'écran ou messages signalés par l'enfant\n• Résultats de l'analyse IA (catégorie, gravité, conseils)\n• District (uniquement si l'enfant demande un soutien-conseiller)\n• Informations de contact (uniquement si l'enfant choisit de se connecter à un conseiller)\n\nNous ne collectons PAS : noms, photos, adresses IP, informations sur l'appareil ou toute donnée d'identification des rapports anonymes.",
    privacyUseTitle: "2. Comment nous utilisons les données",
    privacyUseContent: "Les données sont utilisées uniquement pour :\n\n• Analyser les messages signalés pour la sécurité des enfants\n• Fournir des conseils aux enfants sur la façon de rester en sécurité\n• Connecter les enfants à des conseillers formés lorsque demandé\n• Générer des statistiques nationales anonymes pour la politique de protection de l'enfance\n\nNous ne vendons jamais, ne partageons pas et n'utilisons pas les données à des fins de publicité ou de profilage.",
    privacyProtectTitle: "3. Comment nous protégeons les données",
    privacyProtectContent: "• Toutes les données sont chiffrées en transit (HTTPS) et au repos\n• L'accès est restreint aux conseillers autorisés uniquement\n• La limitation de débit empêche les abus et les attaques automatisées\n• Aucun tracker de suivi ou analytique\n• Code open-source — auditable publiquement",
    privacyChildrenTitle: "4. Confidentialité des enfants",
    privacyChildrenContent: "Mlinzi est conçu spécifiquement pour les enfants. Nous suivons les normes les plus élevées de protection des données des enfants :\n\n• Anonyme par défaut — aucune donnée personnelle requise pour obtenir de l'aide\n• Aucun compte nécessaire pour le signalement de base\n• Le consentement parental n'est pas requis pour le signalement anonyme\n• L'accès au conseiller nécessite le consentement explicite de l'enfant\n• Nous respectons les lois sur la protection des données du Rwanda et les principes de l'UNICEF sur la sécurité numérique des enfants",
    privacyRetentionTitle: "5. Conservation des données",
    privacyRetentionContent: "• Rapports anonymes : conservés jusqu'à 2 ans pour les statistiques nationales\n• Cas liés à un conseiller : conservés jusqu'à 1 an après la résolution\n• Sessions SMS/WhatsApp : supprimées après 90 jours d'inactivité\n• Informations de contact : supprimées immédiatement après la connexion au conseiller\n• Les enfants peuvent demander la suppression à tout moment",
    privacyDeleteTitle: "6. Suppression des données",
    privacyDeleteContent: "Les enfants (ou leurs tuteurs) peuvent demander la suppression complète de leurs données à tout moment en :\n\n• Envoyant un e-mail à privacy@mlinzi.org\n• Envoyant un message à Mlinzi avec 'SUPPRIMER MES DONNÉES'\n• Demandant à leur conseiller de soumettre une demande de suppression\n\nToutes les données seront définitivement supprimées dans les 72 heures suivant la vérification.",
    privacyRightsTitle: "7. Vos droits",
    privacyRightsContent: "Chaque enfant a le droit de :\n\n• Signaler anonymement sans fournir de données personnelles\n• Savoir quelles données ont été collectées le concernant\n• Demander la correction de toute donnée inexacte\n• Demander la suppression complète de ses données\n• Retirer son consentement pour la connexion au conseiller à tout moment\n• Déposer une plainte s'il estime que sa vie privée a été violée",
    privacyContactTitle: "8. Nous contacter",
    privacyContactContent: "Pour les questions sur la confidentialité, les demandes de données ou les plaintes :\n\nE-mail : privacy@mlinzi.org\nTéléphone : +250 788 123 456\nAdresse : UNICEF Rwanda, KG 7 Ave, Kigali\n\nDélégué à la protection des données : dpo@mlinzi.org",
    privacyLastUpdated: "Dernière mise à jour : août 2026 • Une plateforme de protection numérique pour les enfants propulsée par l'IA",
    forgotPasswordTitle: "Mot de passe oublié",
    forgotPasswordDesc: "Entrez votre e-mail et nous vous enverrons un lien de réinitialisation",
    backToLogin: "Retour à la connexion",
    checkEmailTitle: "Vérifiez votre e-mail",
    checkEmailDesc: "Nous avons envoyé un lien de réinitialisation à",
    noEmailCheck: "Vous ne l'avez pas reçu ? Vérifiez vos spams ou réessayez.",
    tryDifferentEmail: "Utiliser un autre e-mail",
    resetYourPassword: "Réinitialiser votre mot de passe",
    enterEmailBelow: "Entrez votre adresse e-mail enregistrée",
    emailAddress: "Adresse e-mail",
    sending: "Envoi...",
    sendResetLink: "Envoyer le lien",
    resetPasswordTitle: "Définir un nouveau mot de passe",
    resetPasswordDesc: "Choisissez un mot de passe fort pour votre compte",
    invalidResetLink: "Lien invalide",
    invalidResetLinkDesc: "Ce lien de réinitialisation est invalide ou a expiré.",
    requestNewLink: "Demander un nouveau lien",
    setNewPassword: "Définir un nouveau mot de passe",
    mustBe8Chars: "Doit contenir au moins 8 caractères",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    passwordsNoMatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
    resetting: "Réinitialisation...",
    passwordResetSuccess: "Réinitialisation réussie",
    passwordResetSuccessDesc: "Votre mot de passe a été mis à jour. Vous pouvez maintenant vous connecter.",
    goToLogin: "Aller à la connexion",
    enterPhoneNumber: "Entrez votre numéro de téléphone",
    otpWillBeSent: "Nous enverrons un code de vérification par SMS",
    phoneLabel: "Numéro de téléphone",
    sendCode: "Envoyer le code",
    enterCode: "Entrez le code de vérification",
    codeSentTo: "Code envoyé à",
    verifying: "Vérification...",
    verifyCode: "Vérifier le code",
    resendIn: "Renvoyer le code dans",
    resendCode: "Renvoyer le code",
    phoneVerified: "Téléphone vérifié",
    phoneVerifiedDesc: "Votre numéro de téléphone a été vérifié. Vous pouvez maintenant définir un nouveau mot de passe.",
    chooseHowToReset: "Comment souhaitez-vous réinitialiser ?",
    chooseChannelDesc: "Choisissez où recevoir votre code de vérification",
    smsOtp: "Code SMS",
    smsOtpDesc: "Recevoir un code à 6 chiffres par SMS",
    emailOtp: "Code e-mail",
    emailOtpDesc: "Recevoir un code à 6 chiffres par e-mail",
    enterEmailAddress: "Entrez votre adresse e-mail",
    verificationVerified: "Vérifié avec succès",
  },
  rw: {
    home: "Ahabanza",
    reportAbuse: "Menya ikibazo",
    login: "Injira",
    logout: "Sohoka",
    cases: "Ibyiciro",
    analytics: "Isesengura",
    admin: "Umuyobozi",
    heroTitle: "Kurinda abana kuri internet",
    heroSubtitle: "Mlinzi yobora abana mu Rwanda gutangaza uburundi bwo kuri internet kandi bakabona ubufasha neza.",
    reportNow: "Menya ikibazo",
    howItWorks: "Uburyo bikorwa",
    step1Title: "Kubika",
    step1Desc: "Fota urupapuro rwoherejwe",
    step2Title: "Kugereranya",
    step2Desc: "AI yacu irasuzuma niba ari ibibazo",
    step3Title: "Kurinda",
    step3Desc: "Shakisha ubufasha utandukane",
    safetyMessage: "Uhumyunyu bwawe bwambere. Ntawari wenyine.",
    analysisResults: "Ibipimo vy'isesengura",
    riskLevel: "Urwego rwo kutera inkunga",
    confidence: "Ishimwe",
    category: "Urwego",
    whatToDo: "Iyo ushobora gukora",
    extractedText: "Inyandiko yakusenywe",
    counselorHelp: "Ushaka ubufasha bwa muganga?",
    stayAnonymous: "Guma utitazwe",
    connectCounselor: "Ndi mu muganga",
    connectWithCounselor: "Uhuze n'umujyanama",
    reportAnother: "Menya undi",
    backToHome: "Subira ahabanza",
    thankYou: "Urakoze gutangaza. Rapporto yawe yobora abana abandi.",
    district: "Akarike",
    selectDistrict: "Hitamwo akarike yawe",
    preferredContact: "Uburyo bwo gutumiza ubutumwa",
    phoneCall: "Itariki",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "Email",
    bestTime: "Igihe gitandukanye",
    bestTimePlaceholder: "urugero: Mu gitondo, Nyuma y'isomo",
    areYouSafe: "Uri mu buzima neza ubu?",
    submitReferral: "Ohereza rapporto",
    contactEncrypted: "Amakuru yawe afite uburindi kandi ategerezwa muganga wemewe gusa.",
    counselorDashboard: "Imbonerahamwe y'umujyanama",
    manageReferrals: "Gucunga raporo kandi ubashe abana bafite ibibazo",
    myCases: "Ibyicuro cyanje",
    unclaimed: "Nta mwanya",
    newCases: "Ibyicuro bishya",
    inReview: "Kuraba neza",
    allStatuses: "Imimerere yose",
    new: "Bishya",
    underReview: "Kuraba neza",
    resolved: "Vyunjwe",
    refresh: "Kugena",
    loadingCases: "Kurera ibyicuro...",
    noCases: "Nta byicuro babonetse",
    noMyCases: "Nta byicuro wasanganye.",
    noUnclaimed: "Ibyicuro vyose byarangiye.",
    claim: "Gushimira",
    viewDetails: "Raba ibisobanuro",
    nationalDashboard: "Imbonerahamwe y'igihugu",
    evidenceInsights: "Amakuru yo kubungabungapolitike n'abayobozi",
    totalReports: "Iraporo vyose vyoherejwe",
    escalatedToCounselors: "vyoherejwe kwa mujyanama",
    highSeverity: "Ibibi bikomeye",
    referrals: "Raporo",
    avgResponse: "Igihe c'ibuze",
    bySeverity: "Kubera ibibi",
    noDataYet: "Nta makuru aho",
    byCategory: "Kubera urwego",
    byDistrict: "Kubera akarike",
    byChannel: "Kubera inzira",
    responseTimeByDistrict: "Igihe c'ibuze ku barike",
    noResponseData: "Nta makuru y'ibuze aho",
    casesLabel: "ibyicuro",
    referralStatus: "Imimerere y'raporo",
    noReferrals: "Nta raporo aho",
    monthlyTrend: "Imigerekezo y'ukwezi",
    dataSummary: "Incamake y'amakuru",
    dataSummaryText: "Iyi imbonerahamwe igaragaza amakuru yose yoherejwe na Mlinzi. Amakuru atsindwa mu gihe runaka. Amakuruose ari amazina kandi agenewe kurinda ubwprivacy bw'abana.",
    safetyAdvice: "IBINDO BY'UMUTEKANO",
    safetyTip1: "Ntumusubire ku mutwe urukware",
    safetyTip2: "Buza uwumutumira",
    safetyTip3: "Fota ugendereze ibyemezo",
    safetyTip4: "Bwira umuntu wemewe",
    safetyTip5: "Ntawari wenyine - ufasha hariho",
    accessibility: "Kuboneka",
    highContrast: "Ibara ryiza cyane",
    largeText: "Inyandiko nkuru",
    language: "Ururimi",
    reportDescription: "Dusobanurire ibyabaye. Rapporto yawe ishobora kuguma atizwe.",
    dropScreenshot: "Teka foto yawe hano",
    typeInstead: "Andika umutwe mu buryo bwangaye",
    analyzing: "Dusuzuma foto yawe...",
    uploadAnalyze: "Kurura ugatonde",
    lowRisk: "Ibibi bike",
    lowRiskMsg: "Umutwe ni mwiza. Uri gukora neza!",
    mediumRisk: "Ibibi bihari",
    mediumRiskMsg: "Umutwe ushobora guhitamo. Dukurinde hamwe.",
    highRisk: "Ibibi bikomeye",
    highRiskMsg: "Umutwe ushobora kuba atari mwiza. Dukurinde hamwe.",
    analyzingReport: "Dusuzuma...",
    aiReviewing: "AI yacu irasuzuma rapporto yawe.",
    actionGuidanceOnly: "Ibyerekezo by'umutekano",
    actionGuidanceOnlyDesc: "Kurikiza ibyerekezo hasi",
    actionAnonymousReport: "Rapporto y'izina ryihishe",
    actionAnonymousReportDesc: "Biyanditswe ku makuru y'igihugu",
    actionConnectCounselor: "Ubufasha bw'umujyanama",
    actionConnectCounselorDesc: "Twitezereye guhuza n'umujyanama",
    actionEmergencyReferral: "Ibanga",
    actionEmergencyReferralDesc: "Nyasha ubufasha bwihuse",
    noReportData: "Nta rapporto yabonetse",
    uploadToStart: "Kurura foto yo gutangira.",
    aiReviewedMsg: "AI yacu irasuzuma umutwe. Dore ibyo twabonye.",
    mlinziAnalysis: "Isesengura rya AI rya Mlinzi",
    whatFoundInMessage: "Ibyo twabonye mu mutwe",
    wouldLikeHelp: "Ushaka ubufasha bwa mujyanama wo kurinda abana?",
    stayAnonymousOrConnect: "Ushobora kuguma utitazwe cyangwa uhuze n'umuntu ushobora kugufasha.",
    keepAnonymous: "Guma utitazwe",
    connectMeCounselor: "Ndi mu mujyanama",
    selectYourDistrict: "Hitamwo akarike yawe",
    contactMethod: "Uburyo bwo gutumiza ubutumwa",
    phoneWhatsappNumber: "Nomero ya telefone/WhatsApp",
    submitting: "Dohereza...",
    contactEncryptedNote: "Amakuru yawe afite uburindi kandi ategerezwa muganga wemewe gusa.",
    imageFileError: "Nyasha urupapuro rwa siyubure (jpg, png, gif, webp).",
    fileSizeError: "Urubuga rugomba kuba ruto cyane 5MB.",
    selectScreenshotOrType: "Nyasha hitamwo foto cyangwa andika umutwe.",
    somethingWrong: "Hari ikosa. Nyashasha.",
    clickOrDropReplace: "Kanda cyangwa teka kugira ngo uhindure",
    orClickBrowse: "cyangwa kanda kugira ngo uje, cyangwa ohereza kubara (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — ubusa 5MB",
    typePasteHarmful: "Andika cyangwa ohereza umutwe mubi hano...",
    typeMessageDirectly: "Ushobora kwandika umutwe mu buryo bwangaye niba foto idakora.",
    anonymousNoData: "100% izina ryihishe — nta makuru yakubiyeho",
    rightThing: "Wakoze neza ukabaza ubufasha.",
    aiWillAnalyze: "AI yacu izasuzuma umutwe kandi itange ibyerekezo vyerekeranye niba ushobora gukora. Uri mu buzima neza hano.",
    counselDashboardSubtitle: "Gucunga raporo kandi ubashe abana bafite ibibazo",
    loadingAnalytics: "Kurera isesengura...",
    unableToLoad: "Ntibashoboye kurera isesengura",
    tryRefreshing: "Nyashasha ugakurura urupapuro.",
    evidenceDesc: "Amakuru yo kubungabunga politike n'abayobozi",
    escalatedCounselors: "vyoherejwe kwa mujyanama",
    loadingCase: "Kurera icuramatsindwi...",
    caseNotFound: "Icuramatsindwi ntarabonetse",
    backToDashboard: "Subira ku imbonerahamwe",
    caseNumber: "Icuramatsindwi #",
    reportDetails: "Ibisobanuro by'iraporo",
    severity: "Ibibi",
    recommended: "Bitegeerezwa",
    aiGuidance: "Ibyerekezo bya AI",
    screenshot: "Foto",
    followUpNotes: "Ibikubiyeho",
    addNotePlaceholder: "Ongeraho inyandiko ku curamatsindwi...",
    adding: "Kongera...",
    addNote: "Kongera inyandiko",
    noNotesYet: "Nta nyandiko aho",
    contactInformation: "Amakuru y'uburambe",
    preferredContactLabel: "Uburambe buhitamwa",
    contactDetails: "Ibisobanuro by'uburambe",
    currentlySafe: "Uri mu buzima neza ubu?",
    timeline: "Igihe",
    submitted: "Yoherejwe",
    aiAnalyzed: "Yasuzumwe na AI",
    counselorAssigned: "Umujyanama yagenewe",
    firstResponse: "Igisubizo c'itangira",
    underReviewTimeline: "Kuraba neza",
    resolvedTimeline: "Vyunjwe",
    guidanceOnly: "Ibyerekezo gusa",
    anonymousReportLabel: "Rapporto y'izina ryihishe",
    connectToCounselor: "Uhuze n'umujyanama",
    emergencyReferralLabel: "Raporo y'ibanga",
    problemSolving: "Ikibazo dushoboye gukemura",
    problemDesc: "Abana mu bushinwa bose bafite ingaruka zikomeye kuri internet, aho ibyo benshi nta buryo bwiza bafise bwo gutangaza uburundi. Amasezerano yo kugenzura ari moke kandi ategerezwa amakuru yakubiyeho.",
    ourPromise: "Igisobanuro twagize",
    promise1: "Izina ryihishe mu buryo bwangaye",
    promise1Desc: "Nta makuru yakubiyeho ashingiye kugira ngo abashe ubufasha",
    promise2: "Ibyerekezo biri ku AI",
    promise2Desc: "Isesengura ryihuse n'ibyerekezo vy'umutekano",
    promise3: "Ubufasha bwa muntu buhariho",
    promise3Desc: "Huza n'abanyenyuzi bamenyerewe niba akenewe",
    promise4: "Icaduranye",
    promise4Desc: "Biraboneka mu Turere, Ifaransa, n'Igikinyarwanda",
    everyChildProtected: "Umwana buri umwe. Ahantu hose. Warindwa.",
    builtForAfrica: "Mlinzi yubakiwe kugira ngo abana bo mu Rwanda n'ubushinwa bose bagenewe. Iri open-source kandi ryateguwe kugira ngo rikure.",
    aiPoweredPlatform: "Umwanya wo kurinda abana biri ku AI",
    unicefProject: "Yubatse kugira ngo isangire n'UNICEF Rwanda n'abandi bakorana nayo • Kurinda. Kwakira. Guhuza.",
    accessMlinzi: "Jya kuri Mlinzi mu buryo bwawe",
    noSmartphone: "Nta telefone? Nta internet? Nta kibazo...",
    webApp: "Apulikasiyo ya Webu",
    webAppDesc: "Kurura foto kandi uje isesengura rya AI mu buryo bushingiye kuri browser.",
    smsDesc: "Ohereza SMS kuri Mlinzi mu buryo bwangaye...",
    whatsappDesc: "Ohereza ubutumwa, foto, n'inkingo mu buryo bwa WhatsApp...",
    oneInThree: "1 kuri 3",
    percent80: "80%",
    statChildren: "abana",
    statReport: "ntabwo batangaza uburundi",
    statOnline: "abana mu bushinwa",
    statOnlineDesc: "bafite ingaruka zikomeye kuri internet",
    statProtected: "barindwa",
    statProtectedDesc: "intego — uburind bwose",
    protect: "Kurinda",
    listen: "Kwakira",
    support: "Gufasha",
    empower: "Gukiza",
    protectDesc: "Isesengura riri ku AI",
    listenDesc: "Kutanga izina ryihishe",
    supportDesc: "Guhuza n'abanyenyuzi",
    empowerDesc: "Amakuru y'umutekano bw'abana",
    unicefInnovation: "Yubatse kugira ngo isangire n'UNICEF Rwanda",
    videoNotSupported: "Browser yawe ntiyakiriye ikibaho cyo kureba.",
    cookieTitle: "Amakuru y'ibanga n'uburindi",
    cookieMessage: "Dukoresha amakuru meza yo kugira ngo Mlinzi irakora neza. Ntakurondera kandi ntakugira ibiro. Ubwemere bwawe bushobora kugufasha twongere ubufasha bw'urukingo rw'abana mu bushinwa.",
    cookieAccept: "Emeza amakuru",
    cookieReject: "Anka",
    privacyTitle: "Politike y'ibanga",
    privacySubtitle: "Uburyo dukoresha amakuru y'abana kandi tumurinde",
    privacyDataTitle: "1. Iryo dukoresha",
    privacyDataContent: "Mlinzi irungika gusa ibisabwa kugira ngo ibashe gufasha abana:\n\n• Amafoto cyangwa ubutumwa bwatanzwe n'umwana\n• Ibipimo vya AI (icuramatsindwi, ibibi, ibyerekezo)\n• Akarike (igihari gusa niba umwana ashaka ubufasha bwa muganga)\n• Amakuru yo guhuza (igihari gusa niba umwana uhitemo guhuza na muganga)\n\nTitwara: amazina, amafoto, adiresi ya IP, amakuru ya foni cyangwa amakuru yo kumenya abanditsa amaporogi.",
    privacyUseTitle: "2. Uburyo dukoresha amakuru",
    privacyUseContent: "Amakuru akoreshejwe gusa kugira ngo:\n\n• Suzuma ubutumwa bwatanzwe kugira ngo umwana ahumyunzwe\n• Tanga ibyerekezo kubana kugira ngo bahumyunzwe\n• Huza abana n'abanyenyuzi niba bisabwa\n• Genereta amakuru y'igihugu atizwe kugira ngo politike y'urukingo rw'abana ishyweho\n\nNtidagurisha, ntigabanya, kandi ntidakoresha amakuru mu guhora cyangwa mu gutondeka.",
    privacyProtectTitle: "3. Uburyo dukoresha amakuru",
    privacyProtectContent: "• Amakuruose arashyirwa mu buzima neza (HTTPS) kandi arakorerwa mu buryo bwangaye\n• Kuboneka gusa abanyenyuzi bemenyerewe\n• Kuboneka mu buryo bwa limite bifasha kurinda amakosa n'ingaruka zikomeye\n• Nta tracker y'ibanga cyangwa y'isesengura\n• Inzego zisobanutse — zishobora gusuzumwa n'ababantu",
    privacyChildrenTitle: "4. Ibangamana ry'abana",
    privacyChildrenContent: "Mlinzi yubakiwe kugira ngo abana bashobore kuyikoresha. Dukurikiza amategeko meza y'urukingo rw'amakuru y'abana:\n\n• Izina ryihishe mu buryo bwangaye — nta makuru yakubiyeho ashingiye kugira ngo abashe ubufasha\n• Nta konti akenewe kugira ngo umuntu atangaze ikibazo\n• Kwemera kw'ababyeyi ntibikenewe kugira ngo umuntu atangaze ikibazo ryihishe\n• Kuboneka ku muganga bushingiye ku kwemera kw'umwana\n• Dukurikiza amategeko y'ibanga y'u Rwanda n'ibyerekezo vya UNICEF ku buhumyunzere bw'abana kuri internet",
    privacyRetentionTitle: "5. Kubika amakuru",
    privacyRetentionContent: "• Iraporo ryihishe: ryabikwa kugeza imyaka 2 kugira ngo amakuru y'igihugu akorewe\n• Ibyiciro vy'abanyenyuzi: vyabikwa kugeza imyaka 1 nyuma y'ikemurwa\n• Amakuru ya SMS/WhatsApp: ahagaritswe nyuma y'ibyumunsi 90 atakoze\n• Amakuru yo guhuza: ahagaritswe vyo aho yoherezwa muganga\n• Abana bashobora kubaza ko amakuru yabo ahagaritswe igihe cose",
    privacyDeleteTitle: "6. Guhindura amakuru",
    privacyDeleteContent: "Abana (cyangwa ababo) bashobora kubaza guhindura amakuru yabo yose igihe cose mu buryo:\n\n• Ohereza email kuri privacy@mlinzi.org\n• Ohereza ubutumwa kuri Mlinzi ukoresheje 'HINDURA AMAKURU YANJE\n• Saba umujyanama wawe ko yohereza icyifuzo cyo guhindura amakuru\n\nAmakuruose azahagaritswe mu minsi 3 nyuma y'kwemezwa.",
    privacyRightsTitle: "7. Uburenganzira bwawe",
    privacyPrivacyRightsContent: "Umwana buri umwe afite uburenganzira bwo:\n\n• Kutangaza izina ryihishe nta makuru yakubiyeho atanga\n• Kumenya amakuru yakubiyeho yerekeranye naye\n• Kubaza ko amakuru amenyekanye atari mu buryo bwangaye\n• Kubaza ko amakuru yose ahagaritswe\n• Guhindura kwemera kw'guhuza na muganga igihe cose\n• Gutanga icyifuzo niba ubwprivacy bwe bwarakoreshejwe nabi",
    privacyContactTitle: "8. Twandikire",
    privacyContactContent: "Kubaza ibibazo vyo kubangamana, icyifuzo cy'amakuru, cyangwa icyifuzo:\n\nEmail: privacy@mlinzi.org\nTelefone: +250 788 123 456\nAderesi: UNICEF Rwanda, KG 7 Ave, Kigali\n\nUmuyobozi w'urukingo rw'amakuru: dpo@mlinzi.org",
    privacyLastUpdated: "Vugurirwa kuwa: Kanama 2026 • Urubuga rukongera abana mu buryo bw'amashanyarazi",
    forgotPasswordTitle: "Wibagiwe ijambo ry'ibanga",
    forgotPasswordDesc: "Injiza email yawe kandi tuzakohereza inkingo yo guhindura",
    backToLogin: "Subira ku ngingo",
    checkEmailTitle: "Suzuma email yawe",
    checkEmailDesc: "Twakohereje inkingo yo guhindura ijambo ry'ibanga kuri",
    noEmailCheck: "Ntiwabonye? Suzuma spam cyangwa ongera ugerageze.",
    tryDifferentEmail: "Koresha email indi",
    resetYourPassword: "Hindura ijambo ry'ibanga",
    enterEmailBelow: "Injiza adiresi ya email yawe",
    emailAddress: "Adiresi ya email",
    sending: "Tumeyeho...",
    sendResetLink: "Ohereza inkingo",
    resetPasswordTitle: "Shira ijambo ry'ibanga rishya",
    resetPasswordDesc: "Hitamwo ijambo ry'ibanga rikomeye kuri konti yawe",
    invalidResetLink: "Inkingo iriyo",
    invalidResetLinkDesc: "Inkingo yo guhindura ijambo ry'ibanga ntiyemewe cyangwa irarangiye.",
    requestNewLink: "Saba inkingo nshya",
    setNewPassword: "Shira ijambo ry'ibanga rishya",
    mustBe8Chars: "Birakenewe byibura inyuguti 8",
    newPassword: "Ijambo ry'ibanga rishya",
    confirmPassword: "Emeza ijambo ry'ibanga",
    passwordsNoMatch: "Ijambo ry'ibanga niryizereye",
    passwordTooShort: "Ijambo ry'ibanga rigomba kuba rifite inyuguti 8",
    resetting: "Duhindura...",
    passwordResetSuccess: "Guhindura byagenze neza",
    passwordResetSuccessDesc: "Ijambo ry'ibanga ryawe ryahinduwe. Ushobora kwinjira noneho.",
    goToLogin: "Jya ku ngingo",
    enterPhoneNumber: "Injiza telefone yawe",
    otpWillBeSent: "Tuzakohereza inkingo yo kwemeza na SMS",
    phoneLabel: "Nomero ya telefone",
    sendCode: "Ohereza inkingo",
    enterCode: "Injiza inkingo yo kwemeza",
    codeSentTo: "Inkingo yoherejwe kuri",
    verifying: "Dukwandikisha...",
    verifyCode: "Emeza inkingo",
    resendIn: "Ongera uohereze inkingo mu",
    resendCode: "Ongera uohereze inkingo",
    phoneVerified: "Telefone yemejwe",
    phoneVerifiedDesc: "Telefone yawe yemejwe. Ushobora noneho guhindura ijambo ry'ibanga.",
    chooseHowToReset: "Ushaka guhindura ute?",
    chooseChannelDesc: "Hitamwo aho ushaka kwakira inkingo yo kwemeza",
    smsOtp: "Inkingo ya SMS",
    smsOtpDesc: "Wakira inkingo y'ibisobanuro 6 na SMS",
    emailOtp: "Inkingo ya email",
    emailOtpDesc: "Wakira inkingo y'ibisobanuro 6 na email",
    enterEmailAddress: "Injiza adiresi ya email yawe",
    verificationVerified: "Yemejwe neza",
  },
};

const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "rw", label: "Kinyarwanda" },
];

const LOCALE_MAP = {
  en: "en-US",
  fr: "fr-FR",
  rw: "rw-RW",
};

export function AccessibilityProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("mlinzi_lang") || "en";
  });
  const [highContrast, setHighContrast] = useState(() => {
    return localStorage.getItem("mlinzi_contrast") === "true";
  });
  const [largeText, setLargeText] = useState(() => {
    return localStorage.getItem("mlinzi_largetext") === "true";
  });

  useEffect(() => {
    localStorage.setItem("mlinzi_lang", language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem("mlinzi_contrast", highContrast);
    document.documentElement.classList.toggle("high-contrast", highContrast);
  }, [highContrast]);

  useEffect(() => {
    localStorage.setItem("mlinzi_largetext", largeText);
    document.documentElement.classList.toggle("large-text", largeText);
  }, [largeText]);

  function t(key) {
    return translations[language]?.[key] || translations.en[key] || key;
  }

  function formatDate(date, options = {}) {
    const locale = LOCALE_MAP[language] || "en-US";
    return new Date(date).toLocaleDateString(locale, options);
  }

  function formatDateTime(date, options = {}) {
    const locale = LOCALE_MAP[language] || "en-US";
    return new Date(date).toLocaleString(locale, options);
  }

  return (
    <AccessibilityContext.Provider
      value={{
        language,
        setLanguage,
        highContrast,
        setHighContrast,
        largeText,
        setLargeText,
        t,
        formatDate,
        formatDateTime,
        languages: LANGUAGES,
      }}
    >
      {children}
    </AccessibilityContext.Provider>
  );
}

export function useAccessibility() {
  const context = useContext(AccessibilityContext);
  if (!context) {
    throw new Error("useAccessibility must be used within AccessibilityProvider");
  }
  return context;
}
