import { createContext, useContext, useState, useEffect } from "react";

const AccessibilityContext = createContext(null);

const translations = {
  en: {
    home: "Home",
    reportAbuse: "Report Abuse",
    login: "Login",
    logout: "Logout",
    cases: "Cases",
    analytics: "Analytics",
    admin: "Admin",
    heroTitle: "Keep Children Safe Online",
    heroSubtitle: "Report online abuse and get help — no account needed. Completely anonymous and free.",
    reportNow: "Report Abuse",
    howItWorks: "How It Works",
    step1Title: "Upload",
    step1Desc: "Take a screenshot of the harmful message",
    step2Title: "Analyze",
    step2Desc: "Our AI checks if it is harmful",
    step3Title: "Protect",
    step3Desc: "Get advice and connect to help",
    safetyMessage: "Your safety comes first. You are not alone.",
    analysisResults: "Analysis Results",
    riskLevel: "Risk Level",
    confidence: "Confidence",
    category: "Category",
    whatToDo: "What You Should Do",
    extractedText: "Extracted Text",
    counselorHelp: "Would you like help from a trained child protection counselor?",
    stayAnonymous: "Keep this anonymous",
    connectCounselor: "Connect me to a counselor",
    connectWithCounselor: "Connect with a Counselor",
    reportAnother: "Report Another",
    backToHome: "Back to Home",
    thankYou: "Thank you for speaking up. Your report helps protect other children too.",
    district: "District",
    selectDistrict: "Select your district",
    preferredContact: "Preferred contact method",
    phoneCall: "Phone call",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "Email",
    bestTime: "Best time to contact",
    bestTimePlaceholder: "e.g., Morning, After school, Anytime",
    areYouSafe: "Are you currently safe?",
    submitReferral: "Submit Referral",
    contactEncrypted: "Your contact information is encrypted and only shared with your assigned counselor.",
    counselorDashboard: "Counselor Dashboard",
    manageReferrals: "Manage referrals and support children in need",
    myCases: "My Cases",
    unclaimed: "Unclaimed",
    newCases: "New Cases",
    inReview: "In Review",
    allStatuses: "All Statuses",
    new: "New",
    underReview: "Under Review",
    resolved: "Resolved",
    refresh: "Refresh",
    loadingCases: "Loading cases...",
    noCases: "No cases found",
    noMyCases: "You don't have any assigned cases yet.",
    noUnclaimed: "All cases have been claimed.",
    claim: "Claim",
    viewDetails: "View Details",
    nationalDashboard: "National Dashboard",
    evidenceInsights: "Evidence-driven insights for policy and decision makers",
    totalReports: "Total Reports Submitted",
    escalatedToCounselors: "escalated to counselors",
    highSeverity: "High Severity",
    referrals: "Referrals",
    avgResponse: "Avg Response",
    bySeverity: "By Severity",
    noDataYet: "No data yet",
    byCategory: "By Category",
    byDistrict: "By District",
    byChannel: "By Channel",
    responseTimeByDistrict: "Response Time by District",
    noResponseData: "No response time data yet",
    casesLabel: "cases",
    referralStatus: "Referral Status",
    noReferrals: "No referrals yet",
    monthlyTrend: "Monthly Trend",
    dataSummary: "Data Summary",
    dataSummaryText: "This dashboard provides an overview of all reports submitted through Mlinzi. Data is updated in real-time as new reports are received. All data is anonymous and aggregated to protect children's privacy. Use these insights to inform policy decisions and allocate resources where they are needed most.",
    safetyAdvice: "SAFETY ADVICE",
    safetyTip1: "Do not reply to the harmful message",
    safetyTip2: "Block the person sending it",
    safetyTip3: "Take a screenshot as evidence",
    safetyTip4: "Tell a trusted adult",
    safetyTip5: "You are not alone - help is available",
    accessibility: "Accessibility",
    highContrast: "High Contrast",
    largeText: "Large Text",
    language: "Language",
    reportDescription: "Tell us what happened. Your report can remain anonymous.",
    dropScreenshot: "Drop your screenshot here",
    typeInstead: "Type the message instead",
    analyzing: "Analyzing your screenshot...",
    uploadAnalyze: "Upload & Analyze",
    lowRisk: "Low Risk",
    lowRiskMsg: "This message appears to be safe. You are doing great!",
    mediumRisk: "Medium Risk",
    mediumRiskMsg: "This message may need attention. Let's protect you together.",
    highRisk: "High Risk",
    highRiskMsg: "This message may be unsafe. Let's protect you together.",
    analyzingReport: "Analyzing...",
    aiReviewing: "Our AI is reviewing your report.",
    actionGuidanceOnly: "Safety Guidance",
    actionGuidanceOnlyDesc: "Follow the safety advice below",
    actionAnonymousReport: "Anonymous Report",
    actionAnonymousReportDesc: "This has been logged for national statistics",
    actionConnectCounselor: "Counselor Support",
    actionConnectCounselorDesc: "We recommend connecting with a counselor",
    actionEmergencyReferral: "Emergency",
    actionEmergencyReferralDesc: "Please seek immediate help",
    noReportData: "No report data found",
    uploadToStart: "Upload a screenshot to get started.",
    aiReviewedMsg: "Our AI has reviewed the message. Here is what we found.",
    mlinziAnalysis: "Mlinzi AI Analysis",
    whatFoundInMessage: "What we found in the message",
    wouldLikeHelp: "Would you like help from a trained child protection counselor?",
    stayAnonymousOrConnect: "You can stay anonymous or connect with someone who can help.",
    keepAnonymous: "Keep this anonymous",
    connectMeCounselor: "Connect me to a counselor",
    selectYourDistrict: "Select your district",
    contactMethod: "Preferred contact method",
    phoneWhatsappNumber: "Phone/WhatsApp number",
    submitting: "Submitting...",
    contactEncryptedNote: "Your contact information is encrypted and only shared with your assigned counselor.",
    imageFileError: "Please upload an image file (jpg, png, gif, webp).",
    fileSizeError: "File must be under 5MB.",
    selectScreenshotOrType: "Please select a screenshot or type the message.",
    somethingWrong: "Something went wrong. Please try again.",
    clickOrDropReplace: "Click or drop to replace",
    orClickBrowse: "or click to browse, or paste from clipboard (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — max 5MB",
    typePasteHarmful: "Type or paste the harmful message here...",
    typeMessageDirectly: "You can type the message directly if the screenshot doesn't work.",
    anonymousNoData: "100% anonymous — no personal data collected",
    rightThing: "You did the right thing by asking for help.",
    aiWillAnalyze: "Our AI will analyze the message and provide clear guidance on what to do next. You are safe here.",
    counselDashboardSubtitle: "Manage referrals and support children in need",
    loadingAnalytics: "Loading analytics...",
    unableToLoad: "Unable to load analytics",
    tryRefreshing: "Please try refreshing the page.",
    evidenceDesc: "Evidence-driven insights for policy and decision makers",
    escalatedCounselors: "escalated to counselors",
    loadingCase: "Loading case...",
    caseNotFound: "Case not found",
    backToDashboard: "Back to Dashboard",
    caseNumber: "Case #",
    reportDetails: "Report Details",
    severity: "Severity",
    recommended: "Recommended",
    aiGuidance: "AI Guidance",
    screenshot: "Screenshot",
    followUpNotes: "Follow-up Notes",
    addNotePlaceholder: "Add a note about this case...",
    adding: "Adding...",
    addNote: "Add Note",
    noNotesYet: "No notes yet",
    contactInformation: "Contact Information",
    preferredContactLabel: "Preferred Contact",
    contactDetails: "Contact Details",
    currentlySafe: "Currently Safe?",
    timeline: "Timeline",
    submitted: "Submitted",
    aiAnalyzed: "AI Analyzed",
    counselorAssigned: "Counselor Assigned",
    firstResponse: "First Response",
    underReviewTimeline: "Under Review",
    resolvedTimeline: "Resolved",
    guidanceOnly: "Guidance Only",
    anonymousReportLabel: "Anonymous Report",
    connectToCounselor: "Connect to Counselor",
    emergencyReferralLabel: "Emergency Referral",
    problemSolving: "The Problem We're Solving",
    problemDesc: "Children across Africa face growing threats online, yet most lack safe ways to report abuse. Existing systems are slow, require personal data, and fail to reach children in rural communities.",
    ourPromise: "Our Promise to You",
    promise1: "Anonymous by default",
    promise1Desc: "No personal data required to get help",
    promise2: "AI-powered guidance",
    promise2Desc: "Instant analysis and safety advice",
    promise3: "Human support available",
    promise3Desc: "Connect with trained counselors when needed",
    promise4: "Multilingual",
    promise4Desc: "Available in English, French, and Kinyarwanda",
    everyChildProtected: "Every child. Everywhere. Protected.",
    builtForAfrica: "Mlinzi is built for children across Rwanda and Africa. Open-source, community-driven, and designed to scale to protect every child online.",
    aiPoweredPlatform: "AI-powered child digital protection platform",
    unicefProject: "Designed for UNICEF Rwanda & partners • Protect. Listen. Connect.",
    accessMlinzi: "Access Mlinzi Your Way",
    noSmartphone: "No smartphone? No internet? No problem...",
    webApp: "Web App",
    webAppDesc: "Upload screenshots and get instant AI analysis on any device with a browser.",
    smsDesc: "Text Mlinzi from any basic phone...",
    whatsappDesc: "Send messages, screenshots, and voice notes through WhatsApp...",
    oneInThree: "1 in 3",
    percent80: "80%",
    statChildren: "children",
    statReport: "never report abuse",
    statOnline: "of children in Africa",
    statOnlineDesc: "face online risks",
    statProtected: "protected",
    statProtectedDesc: "target — universal coverage",
    protect: "Protect",
    listen: "Listen",
    support: "Support",
    empower: "Empower",
    protectDesc: "AI-powered analysis",
    listenDesc: "Anonymous reporting",
    supportDesc: "Counselor connections",
    empowerDesc: "Child safety resources",
    unicefInnovation: "Designed for UNICEF Rwanda",
    videoNotSupported: "Your browser does not support the video tag.",
    cookieTitle: "Cookies & Privacy",
    cookieMessage: "We use essential cookies to keep Mlinzi running safely. We do not track you or share your data. By accepting, you help us improve child protection services across Africa.",
    cookieAccept: "Accept Cookies",
    cookieReject: "Reject",
    privacyTitle: "Privacy Policy",
    privacySubtitle: "How we protect children's data and privacy",
    privacyDataTitle: "1. What We Collect",
    privacyDataContent: "Mlinzi collects only what is needed to help children:\n\n• Screenshots or text messages reported by the child\n• AI analysis results (category, severity, guidance)\n• District (only if the child requests counselor support)\n• Contact information (only if the child chooses to connect with a counselor)\n\nWe do NOT collect: names, photos, IP addresses, device information, or any identifying data from anonymous reports.",
    privacyUseTitle: "2. How We Use Data",
    privacyUseContent: "Data is used solely to:\n\n• Analyze reported messages for child safety\n• Provide guidance to children on how to stay safe\n• Connect children with trained counselors when requested\n• Generate anonymous national statistics for child protection policy\n\nWe never sell, share, or use data for advertising or profiling.",
    privacyProtectTitle: "3. How We Protect Data",
    privacyProtectContent: "• All data is encrypted in transit (HTTPS) and at rest\n• Access is restricted to authorized counselors only\n• Rate limiting prevents abuse and automated attacks\n• No tracking cookies or analytics trackers\n• Open-source code — publicly auditable",
    privacyChildrenTitle: "4. Children's Privacy",
    privacyChildrenContent: "Mlinzi is designed specifically for children. We follow the highest standards of child data protection:\n\n• Anonymous by default — no personal data required to get help\n• No accounts needed for basic reporting\n• Parental consent is not required for anonymous reporting\n• Counselor access requires explicit child consent\n• We comply with Rwanda's data protection laws and UNICEF's principles on children's digital safety",
    privacyRetentionTitle: "5. Data Retention",
    privacyRetentionContent: "• Anonymous reports: retained for up to 2 years for national statistics\n• Counselor-linked cases: retained for up to 1 year after case resolution\n• SMS/WhatsApp sessions: deleted after 90 days of inactivity\n• Contact information: deleted immediately after counselor connection\n• Children can request deletion at any time",
    privacyDeleteTitle: "6. Data Deletion",
    privacyDeleteContent: "Children (or their guardians) can request full deletion of their data at any time by:\n\n• Emailing privacy@mlinzi.org\n• Messaging Mlinzi with 'DELETE MY DATA'\n• Asking their counselor to submit a deletion request\n\nAll data will be permanently deleted within 72 hours of verification.",
    privacyRightsTitle: "7. Your Rights",
    privacyRightsContent: "Every child has the right to:\n\n• Report anonymously without providing any personal data\n• Know what data has been collected about them\n• Request correction of any inaccurate data\n• Request full deletion of their data\n• Withdraw consent for counselor connection at any time\n• File a complaint if they believe their privacy has been violated",
    privacyContactTitle: "8. Contact Us",
    privacyContactContent: "For privacy questions, data requests, or complaints:\n\nEmail: privacy@mlinzi.org\nPhone: +250 788 123 456\nAddress: UNICEF Rwanda, KG 7 Ave, Kigali\n\nData Protection Officer: dpo@mlinzi.org",
    privacyLastUpdated: "Last updated: August 2026 • A proposed AI-powered child digital protection platform",
    forgotPasswordTitle: "Forgot Password",
    forgotPasswordDesc: "Enter your email and we'll send you a reset link",
    backToLogin: "Back to Login",
    checkEmailTitle: "Check Your Email",
    checkEmailDesc: "We sent a password reset link to",
    noEmailCheck: "Didn't receive it? Check your spam folder or try again.",
    tryDifferentEmail: "Use a different email",
    resetYourPassword: "Reset Your Password",
    enterEmailBelow: "Enter your registered email address",
    emailAddress: "Email Address",
    sending: "Sending...",
    sendResetLink: "Send Reset Link",
    resetPasswordTitle: "Set New Password",
    resetPasswordDesc: "Choose a strong password for your account",
    invalidResetLink: "Invalid Reset Link",
    invalidResetLinkDesc: "This password reset link is invalid or has expired.",
    requestNewLink: "Request a New Link",
    setNewPassword: "Set New Password",
    mustBe8Chars: "Must be at least 8 characters",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordsNoMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 8 characters",
    resetting: "Resetting...",
    passwordResetSuccess: "Password Reset Successful",
    passwordResetSuccessDesc: "Your password has been updated. You can now log in with your new password.",
    goToLogin: "Go to Login",
    enterPhoneNumber: "Enter Your Phone Number",
    otpWillBeSent: "We'll send a verification code via SMS",
    phoneLabel: "Phone Number",
    sendCode: "Send Code",
    enterCode: "Enter Verification Code",
    codeSentTo: "Code sent to",
    verifying: "Verifying...",
    verifyCode: "Verify Code",
    resendIn: "Resend code in",
    resendCode: "Resend Code",
    phoneVerified: "Phone Verified",
    phoneVerifiedDesc: "Your phone number has been verified. You can now set a new password.",
    chooseHowToReset: "How Would You Like to Reset?",
    chooseChannelDesc: "Choose where to receive your verification code",
    smsOtp: "SMS Code",
    smsOtpDesc: "Receive a 6-digit code via text message",
    emailOtp: "Email Code",
    emailOtpDesc: "Receive a 6-digit code via email",
    enterEmailAddress: "Enter Your Email Address",
    verificationVerified: "Verified Successfully",
  },
  fr: {
    home: "Accueil",
    reportAbuse: "Signaler un abus",
    login: "Connexion",
    logout: "Déconnexion",
    cases: "Cas",
    analytics: "Analytique",
    admin: "Admin",
    heroTitle: "Protéger les enfants en ligne",
    heroSubtitle: "Signalez les abus en ligne et obtenez de l'aide — aucun compte nécessaire. Anonyme et gratuit.",
    reportNow: "Signaler un abus",
    howItWorks: "Comment ça marche",
    step1Title: "Télécharger",
    step1Desc: "Prenez une capture d'écran du message nocif",
    step2Title: "Analyser",
    step2Desc: "Notre IA vérifie si c'est nocif",
    step3Title: "Protéger",
    step3Desc: "Obtenez des conseils et connectez-vous à l'aide",
    safetyMessage: "Votre sécurité passe en premier. Vous n'êtes pas seul.",
    analysisResults: "Résultats de l'analyse",
    riskLevel: "Niveau de risque",
    confidence: "Confiance",
    category: "Catégorie",
    whatToDo: "Ce que vous devriez faire",
    extractedText: "Texte extrait",
    counselorHelp: "Aimeriez-vous de l'aide d'un conseiller en protection de l'enfance?",
    stayAnonymous: "Rester anonyme",
    connectCounselor: "Me connecter à un conseiller",
    connectWithCounselor: "Se connecter à un conseiller",
    reportAnother: "Signaler un autre",
    backToHome: "Retour à l'accueil",
    thankYou: "Merci de parler. Votre rapport aide à protéger d'autres enfants aussi.",
    district: "District",
    selectDistrict: "Sélectionnez votre district",
    preferredContact: "Méthode de contact préférée",
    phoneCall: "Appel téléphonique",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "E-mail",
    bestTime: "Meilleur moment pour vous contacter",
    bestTimePlaceholder: "ex., Matin, Après l'école, N'importe quand",
    areYouSafe: "Êtes-vous en sécurité actuellement?",
    submitReferral: "Soumettre le referral",
    contactEncrypted: "Vos informations de contact sont cryptées et partagées uniquement avec votre conseiller assigné.",
    counselorDashboard: "Tableau de bord du conseiller",
    manageReferrals: "Gérer les referrals et soutenir les enfants dans le besoin",
    myCases: "Mes cas",
    unclaimed: "Non réclamés",
    newCases: "Nouveaux cas",
    inReview: "En revue",
    allStatuses: "Tous les statuts",
    new: "Nouveau",
    underReview: "En revue",
    resolved: "Résolu",
    refresh: "Rafraîchir",
    loadingCases: "Chargement des cas...",
    noCases: "Aucun cas trouvé",
    noMyCases: "Vous n'avez pas encore de cas assignés.",
    noUnclaimed: "Tous les cas ont été réclamés.",
    claim: "Réclamer",
    viewDetails: "Voir les détails",
    nationalDashboard: "Tableau de bord national",
    evidenceInsights: "Aperçus fondés sur des preuves pour les décideurs politiques",
    totalReports: "Total des rapports soumis",
    escalatedToCounselors: "escaladés aux conseillers",
    highSeverity: "Haute gravité",
    referrals: "Referrals",
    avgResponse: "Temps de réponse moyen",
    bySeverity: "Par gravité",
    noDataYet: "Pas encore de données",
    byCategory: "Par catégorie",
    byDistrict: "Par district",
    byChannel: "Par canal",
    responseTimeByDistrict: "Temps de réponse par district",
    noResponseData: "Pas encore de données de réponse",
    casesLabel: "cas",
    referralStatus: "Statut des referrals",
    noReferrals: "Pas encore de referrals",
    monthlyTrend: "Tendance mensuelle",
    dataSummary: "Résumé des données",
    dataSummaryText: "Ce tableau de bord fournit un aperçu de tous les rapports soumis via Mlinzi. Les données sont mises à jour en temps réel. Toutes les données sont anonymes et agrégées pour protéger la vie privée des enfants.",
    safetyAdvice: "CONSEILS DE SÉCURITÉ",
    safetyTip1: "Ne répondez pas au message nocif",
    safetyTip2: "Bloquez la personne qui l'envoie",
    safetyTip3: "Prenez une capture d'écran comme preuve",
    safetyTip4: "Parlez-en à un adulte de confiance",
    safetyTip5: "Vous n'êtes pas seul - de l'aide est disponible",
    accessibility: "Accessibilité",
    highContrast: "Contraste élevé",
    largeText: "Grand texte",
    language: "Langue",
    reportDescription: "Dites-nous ce qui s'est passé. Votre rapport peut rester anonyme.",
    dropScreenshot: "Déposez votre capture d'écran ici",
    typeInstead: "Tapez le message à la place",
    analyzing: "Analyse de votre capture d'écran...",
    uploadAnalyze: "Télécharger et analyser",
    lowRisk: "Faible risque",
    lowRiskMsg: "Ce message semble sûr. Vous faites du bon travail!",
    mediumRisk: "Risque moyen",
    mediumRiskMsg: "Ce message peut nécessiter une attention. Protégeons-vous ensemble.",
    highRisk: "Risque élevé",
    highRiskMsg: "Ce message peut être dangereux. Protégeons-vous ensemble.",
    analyzingReport: "Analyse...",
    aiReviewing: "Notre IA examine votre rapport.",
    actionGuidanceOnly: "Conseils de sécurité",
    actionGuidanceOnlyDesc: "Suivez les conseils de sécurité ci-dessous",
    actionAnonymousReport: "Rapport anonyme",
    actionAnonymousReportDesc: "Cela a été enregistré pour les statistiques nationales",
    actionConnectCounselor: "Soutien du conseiller",
    actionConnectCounselorDesc: "Nous vous recommandons de vous connecter à un conseiller",
    actionEmergencyReferral: "Urgence",
    actionEmergencyReferralDesc: "Veuillez chercher une aide immédiate",
    noReportData: "Aucune donnée de rapport trouvée",
    uploadToStart: "Téléchargez une capture d'écran pour commencer.",
    aiReviewedMsg: "Notre IA a examiné le message. Voici ce que nous avons trouvé.",
    mlinziAnalysis: "Analyse IA Mlinzi",
    whatFoundInMessage: "Ce que nous avons trouvé dans le message",
    wouldLikeHelp: "Aimeriez-vous de l'aide d'un conseiller en protection de l'enfance?",
    stayAnonymousOrConnect: "Vous pouvez rester anonyme ou vous connecter avec quelqu'un qui peut aider.",
    keepAnonymous: "Rester anonyme",
    connectMeCounselor: "Me connecter à un conseiller",
    selectYourDistrict: "Sélectionnez votre district",
    contactMethod: "Méthode de contact préférée",
    phoneWhatsappNumber: "Numéro de téléphone/WhatsApp",
    submitting: "Soumission...",
    contactEncryptedNote: "Vos informations de contact sont cryptées et partagées uniquement avec votre conseiller assigné.",
    imageFileError: "Veuillez télécharger un fichier image (jpg, png, gif, webp).",
    fileSizeError: "Le fichier doit être inférieur à 5 Mo.",
    selectScreenshotOrType: "Veuillez sélectionner une capture d'écran ou taper le message.",
    somethingWrong: "Une erreur s'est produite. Veuillez réessayer.",
    clickOrDropReplace: "Cliquez ou déposez pour remplacer",
    orClickBrowse: "ou cliquez pour parcourir, ou collez du presse-papiers (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — max 5 Mo",
    typePasteHarmful: "Tapez ou collez le message nocif ici...",
    typeMessageDirectly: "Vous pouvez taper le message directement si la capture d'écran ne fonctionne pas.",
    anonymousNoData: "100% anonyme — aucune donnée personnelle collectée",
    rightThing: "Vous avez bien fait de demander de l'aide.",
    aiWillAnalyze: "Notre IA analysera le message et fournira des conseils clairs sur la suite. Vous êtes en sécurité ici.",
    counselDashboardSubtitle: "Gérer les referrals et soutenir les enfants dans le besoin",
    loadingAnalytics: "Chargement des analytiques...",
    unableToLoad: "Impossible de charger les analytiques",
    tryRefreshing: "Veuillez rafraîchir la page.",
    evidenceDesc: "Aperçus fondés sur des preuves pour les décideurs politiques",
    escalatedCounselors: "escaladés aux conseillers",
    loadingCase: "Chargement du cas...",
    caseNotFound: "Cas non trouvé",
    backToDashboard: "Retour au tableau de bord",
    caseNumber: "Cas #",
    reportDetails: "Détails du rapport",
    severity: "Gravité",
    recommended: "Recommandé",
    aiGuidance: "Conseils IA",
    screenshot: "Capture d'écran",
    followUpNotes: "Notes de suivi",
    addNotePlaceholder: "Ajoutez une note sur ce cas...",
    adding: "Ajout...",
    addNote: "Ajouter une note",
    noNotesYet: "Pas encore de notes",
    contactInformation: "Informations de contact",
    preferredContactLabel: "Contact préféré",
    contactDetails: "Détails du contact",
    currentlySafe: "En sécurité actuellement?",
    timeline: "Chronologie",
    submitted: "Soumis",
    aiAnalyzed: "Analysé par IA",
    counselorAssigned: "Conseiller assigné",
    firstResponse: "Première réponse",
    underReviewTimeline: "En revue",
    resolvedTimeline: "Résolu",
    guidanceOnly: "Conseils uniquement",
    anonymousReportLabel: "Rapport anonyme",
    connectToCounselor: "Se connecter à un conseiller",
    emergencyReferralLabel: "Referral d'urgence",
    problemSolving: "Le problème que nous résolvons",
    problemDesc: "Les enfants à travers l'Afrique font face à des menaces croissantes en ligne, mais la plupart n'ont pas de moyens sûrs de signaler les abus. Les systèmes existants sont lents, nécessitent des données personnelles et ne parviennent pas aux enfants des communautés rurales.",
    ourPromise: "Notre promesse pour vous",
    promise1: "Anonyme par défaut",
    promise1Desc: "Aucune donnée personnelle requise pour obtenir de l'aide",
    promise2: "Guidage propulsé par IA",
    promise2Desc: "Analyse instantanée et conseils de sécurité",
    promise3: "Soutien humain disponible",
    promise3Desc: "Connectez-vous avec des conseillers formés si nécessaire",
    promise4: "Multilingue",
    promise4Desc: "Disponible en anglais, français et kinyarwanda",
    everyChildProtected: "Chaque enfant. Partout. Protégé.",
    builtForAfrica: "Mlinzi est construit pour les enfants à travers le Rwanda et l'Afrique. Open-source, communautaire et conçu pour se développer pour protéger chaque enfant en ligne.",
    aiPoweredPlatform: "Plateforme de protection numérique de l'enfant propulsée par l'IA",
    unicefProject: "Conçu pour l'UNICEF Rwanda et ses partenaires • Protéger. Écouter. Connecter.",
    accessMlinzi: "Accédez à Mlinzi à votre façon",
    noSmartphone: "Pas de smartphone? Pas d'internet? Pas de problème...",
    webApp: "Application Web",
    webAppDesc: "Téléchargez des captures d'écran et obtenez une analyse IA instantanée sur n'importe quel appareil avec un navigateur.",
    smsDesc: "Envoyez un SMS à Mlinzi depuis n'importe quel téléphone...",
    whatsappDesc: "Envoyez des messages, des captures d'écran et des notes vocales via WhatsApp...",
    oneInThree: "1 sur 3",
    percent80: "80%",
    statChildren: "enfants",
    statReport: "ne signalent jamais les abus",
    statOnline: "des enfants en Afrique",
    statOnlineDesc: "font face à des risques en ligne",
    statProtected: "protégés",
    statProtectedDesc: "cible — couverture universelle",
    protect: "Protéger",
    listen: "Écouter",
    support: "Soutenir",
    empower: "Autonomiser",
    protectDesc: "Analyse propulsée par l'IA",
    listenDesc: "Signalement anonyme",
    supportDesc: "Connexions avec des conseillers",
    empowerDesc: "Ressources de sécurité des enfants",
    unicefInnovation: "Conçu pour l'UNICEF Rwanda",
    videoNotSupported: "Votre navigateur ne prend pas en charge la balise vidéo.",
    cookieTitle: "Cookies et confidentialité",
    cookieMessage: "Nous utilisons des cookies essentiels pour garder Mlinzi en fonctionnement en toute sécurité. Nous ne vous suivons pas et ne partageons pas vos données. En acceptant, vous nous aidez à améliorer les services de protection de l'enfance en Afrique.",
    cookieAccept: "Accepter les cookies",
    cookieReject: "Refuser",
    privacyTitle: "Politique de confidentialité",
    privacySubtitle: "Comment nous protégeons les données et la vie privée des enfants",
    privacyDataTitle: "1. Ce que nous collectons",
    privacyDataContent: "Mlinzi ne collecte que ce qui est nécessaire pour aider les enfants :\n\n• Captures d'écran ou messages signalés par l'enfant\n• Résultats de l'analyse IA (catégorie, gravité, conseils)\n• District (uniquement si l'enfant demande un soutien-conseiller)\n• Informations de contact (uniquement si l'enfant choisit de se connecter à un conseiller)\n\nNous ne collectons PAS : noms, photos, adresses IP, informations sur l'appareil ou toute donnée d'identification des rapports anonymes.",
    privacyUseTitle: "2. Comment nous utilisons les données",
    privacyUseContent: "Les données sont utilisées uniquement pour :\n\n• Analyser les messages signalés pour la sécurité des enfants\n• Fournir des conseils aux enfants sur la façon de rester en sécurité\n• Connecter les enfants à des conseillers formés lorsque demandé\n• Générer des statistiques nationales anonymes pour la politique de protection de l'enfance\n\nNous ne vendons jamais, ne partageons pas et n'utilisons pas les données à des fins de publicité ou de profilage.",
    privacyProtectTitle: "3. Comment nous protégeons les données",
    privacyProtectContent: "• Toutes les données sont chiffrées en transit (HTTPS) et au repos\n• L'accès est restreint aux conseillers autorisés uniquement\n• La limitation de débit empêche les abus et les attaques automatisées\n• Aucun tracker de suivi ou analytique\n• Code open-source — auditable publiquement",
    privacyChildrenTitle: "4. Confidentialité des enfants",
    privacyChildrenContent: "Mlinzi est conçu spécifiquement pour les enfants. Nous suivons les normes les plus élevées de protection des données des enfants :\n\n• Anonyme par défaut — aucune donnée personnelle requise pour obtenir de l'aide\n• Aucun compte nécessaire pour le signalement de base\n• Le consentement parental n'est pas requis pour le signalement anonyme\n• L'accès au conseiller nécessite le consentement explicite de l'enfant\n• Nous respectons les lois sur la protection des données du Rwanda et les principes de l'UNICEF sur la sécurité numérique des enfants",
    privacyRetentionTitle: "5. Conservation des données",
    privacyRetentionContent: "• Rapports anonymes : conservés jusqu'à 2 ans pour les statistiques nationales\n• Cas liés à un conseiller : conservés jusqu'à 1 an après la résolution\n• Sessions SMS/WhatsApp : supprimées après 90 jours d'inactivité\n• Informations de contact : supprimées immédiatement après la connexion au conseiller\n• Les enfants peuvent demander la suppression à tout moment",
    privacyDeleteTitle: "6. Suppression des données",
    privacyDeleteContent: "Les enfants (ou leurs tuteurs) peuvent demander la suppression complète de leurs données à tout moment en :\n\n• Envoyant un e-mail à privacy@mlinzi.org\n• Envoyant un message à Mlinzi avec 'SUPPRIMER MES DONNÉES'\n• Demandant à leur conseiller de soumettre une demande de suppression\n\nToutes les données seront définitivement supprimées dans les 72 heures suivant la vérification.",
    privacyRightsTitle: "7. Vos droits",
    privacyRightsContent: "Chaque enfant a le droit de :\n\n• Signaler anonymement sans fournir de données personnelles\n• Savoir quelles données ont été collectées le concernant\n• Demander la correction de toute donnée inexacte\n• Demander la suppression complète de ses données\n• Retirer son consentement pour la connexion au conseiller à tout moment\n• Déposer une plainte s'il estime que sa vie privée a été violée",
    privacyContactTitle: "8. Nous contacter",
    privacyContactContent: "Pour les questions sur la confidentialité, les demandes de données ou les plaintes :\n\nE-mail : privacy@mlinzi.org\nTéléphone : +250 788 123 456\nAdresse : UNICEF Rwanda, KG 7 Ave, Kigali\n\nDélégué à la protection des données : dpo@mlinzi.org",
    privacyLastUpdated: "Dernière mise à jour : août 2026 • Une plateforme de protection numérique pour les enfants propulsée par l'IA",
    forgotPasswordTitle: "Mot de passe oublié",
    forgotPasswordDesc: "Entrez votre e-mail et nous vous enverrons un lien de réinitialisation",
    backToLogin: "Retour à la connexion",
    checkEmailTitle: "Vérifiez votre e-mail",
    checkEmailDesc: "Nous avons envoyé un lien de réinitialisation à",
    noEmailCheck: "Vous ne l'avez pas reçu ? Vérifiez vos spams ou réessayez.",
    tryDifferentEmail: "Utiliser un autre e-mail",
    resetYourPassword: "Réinitialiser votre mot de passe",
    enterEmailBelow: "Entrez votre adresse e-mail enregistrée",
    emailAddress: "Adresse e-mail",
    sending: "Envoi...",
    sendResetLink: "Envoyer le lien",
    resetPasswordTitle: "Définir un nouveau mot de passe",
    resetPasswordDesc: "Choisissez un mot de passe fort pour votre compte",
    invalidResetLink: "Lien invalide",
    invalidResetLinkDesc: "Ce lien de réinitialisation est invalide ou a expiré.",
    requestNewLink: "Demander un nouveau lien",
    setNewPassword: "Définir un nouveau mot de passe",
    mustBe8Chars: "Doit contenir au moins 8 caractères",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    passwordsNoMatch: "Les mots de passe ne correspondent pas",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
    resetting: "Réinitialisation...",
    passwordResetSuccess: "Réinitialisation réussie",
    passwordResetSuccessDesc: "Votre mot de passe a été mis à jour. Vous pouvez maintenant vous connecter.",
    goToLogin: "Aller à la connexion",
    enterPhoneNumber: "Entrez votre numéro de téléphone",
    otpWillBeSent: "Nous enverrons un code de vérification par SMS",
    phoneLabel: "Numéro de téléphone",
    sendCode: "Envoyer le code",
    enterCode: "Entrez le code de vérification",
    codeSentTo: "Code envoyé à",
    verifying: "Vérification...",
    verifyCode: "Vérifier le code",
    resendIn: "Renvoyer le code dans",
    resendCode: "Renvoyer le code",
    phoneVerified: "Téléphone vérifié",
    phoneVerifiedDesc: "Votre numéro de téléphone a été vérifié. Vous pouvez maintenant définir un nouveau mot de passe.",
    chooseHowToReset: "Comment souhaitez-vous réinitialiser ?",
    chooseChannelDesc: "Choisissez où recevoir votre code de vérification",
    smsOtp: "Code SMS",
    smsOtpDesc: "Recevoir un code à 6 chiffres par SMS",
    emailOtp: "Code e-mail",
    emailOtpDesc: "Recevoir un code à 6 chiffres par e-mail",
    enterEmailAddress: "Entrez votre adresse e-mail",
    verificationVerified: "Vérifié avec succès",
  },
  rw: {
    home: "Ahabanza",
    reportAbuse: "Tanga Raporo",
    login: "Injira",
    logout: "Sohoka",
    cases: "Ibyiciro",
    analytics: "Isesengura",
    admin: "Umuyobozi",
    heroTitle: "Rinda Abana kuri Interineti",
    heroSubtitle: "Tanga raporo y'ihohoterwa kuri interineti ubone ubufasha — nta konti ikenewe. Ari ibanga kandi bitagura.",
    reportNow: "Tanga Raporo",
    howItWorks: "Uburyo Bikorwa",
    step1Title: "Ohereza",
    step1Desc: "Fata ikibazo cy'ikiganiro cy'ubutumwa bubi",
    step2Title: "Isesengura",
    step2Desc: "AI yacu isuzuma niba ari ikibazo",
    step3Title: "Kurinda",
    step3Desc: "Bona inama kandi uhuze n'ubufasha",
    safetyMessage: "Umutekano wawe uza mbere. Ntuwari wenyine.",
    analysisResults: "Ibisubizo by'isesengura",
    riskLevel: "Urwego rw'ingaruka",
    confidence: "Ukwizera",
    category: "Icyiciro",
    whatToDo: "Ibyo ugomba gukora",
    extractedText: "Inyandiko yakuwe",
    counselorHelp: "Ushaka ubufasha bw'umujyanama w'urukingo rw'abana?",
    stayAnonymous: "Guma ari ibanga",
    connectCounselor: "Njyanye ku mujyanama",
    connectWithCounselor: "Huza n'Umujyanama",
    reportAnother: "Tanga indi raporo",
    backToHome: "Subira ku Itangiriro",
    thankYou: "Urakoze kuvuga. Raporo yawe ifasha kurinda abandi bana.",
    district: "Akarere",
    selectDistrict: "Hitamwo akarere kawe",
    preferredContact: "Uburyo bwo gutumanahana bwihitiyemo",
    phoneCall: "Guhamagara",
    sms: "SMS",
    whatsapp: "WhatsApp",
    email: "Imeri",
    bestTime: "Igihe cyiza cyo gutumanahana",
    bestTimePlaceholder: "urugero: Mu gitondo, Nyuma y'isomo, Igihe cyose",
    areYouSafe: "Uri mu mutekano ubu?",
    submitReferral: "Ohereza Raporo",
    contactEncrypted: "Amakuru yawe yo gutumanahana ashyizwe mu banga kandi asangirwa n'umujyanama wawe gusa.",
    counselorDashboard: "Imbonerahamwe y'Umujyanama",
    manageReferrals: "Gucunga raporo no gufasha abana bakeneye ubufasha",
    myCases: "Ibyiciro Byanjye",
    unclaimed: "Bitafashwe",
    newCases: "Ibyiciro Bishya",
    inReview: "Birimo Gusuzumwa",
    allStatuses: "Imimerere Yose",
    new: "Bishya",
    underReview: "Birimo Gusuzumwa",
    resolved: "Byakemutse",
    refresh: "Kuvugurura",
    loadingCases: "Gutegura ibyiciro...",
    noCases: "Nta byiciro byabonetse",
    noMyCases: "Nta byiciro wahawe kugeza ubu.",
    noUnclaimed: "Ibyiciro byose bifashwe.",
    claim: "Fata",
    viewDetails: "Reba Ibisobanuro",
    nationalDashboard: "Imbonerahamwe y'Igihugu",
    evidenceInsights: "Amakuru ashingiye ku bimenyetso ku bayobozi b'inzego",
    totalReports: "Raporo Zose Zoherejwe",
    escalatedToCounselors: "zoherejwe ku bajyanama",
    highSeverity: "Ingaruka Zikomeye",
    referrals: "Raporo z'Ihuza",
    avgResponse: "Igihe Gisanzwe cyo Gusubiza",
    bySeverity: "Hakurikijwe Ingaruka",
    noDataYet: "Nta makuru arahari",
    byCategory: "Hakurikijwe Icyiciro",
    byDistrict: "Hakurikijwe Akarere",
    byChannel: "Hakurikijwe Inzira",
    responseTimeByDistrict: "Igihe cyo Gusubiza ku Karere",
    noResponseData: "Nta makuru y'igihe cyo gusubiza arahari",
    casesLabel: "ibyiciro",
    referralStatus: "Imimerere ya Raporo",
    noReferrals: "Nta raporo z'ihuza zirahari",
    monthlyTrend: "Imibare y'Ukwezi",
    dataSummary: "Incamake y'Amakuru",
    dataSummaryText: "Iyi mbonerahamwe igaragaza amakuru yose yoherejwe na Mlinzi. Amakuru avugururwa igihe cyose raporo nshya ikinjira. Amakuru yose ntiyerekana amazina kandi agenewe kurinda ubwihishurire bw'abana. Koresha izi makuru kugirango ufate ibyemezo bya politiki no gushyira imitungo ahantu ikenewe.",
    safetyAdvice: "INAMA Z'UMUTEKANO",
    safetyTip1: "Ntimusubize ubutumwa bubi",
    safetyTip2: "Buza uwakutwikiye ubutumwa",
    safetyTip3: "Fata ikibazo nk'ibimenyetso",
    safetyTip4: "Bwira umukuru ukwizera",
    safetyTip5: "Ntuwari wenyine — ubufasha buhari",
    accessibility: "Kugera ku Makuru",
    highContrast: "Ibara Ryinshi",
    largeText: "Inyandiko Nini",
    language: "Ururimi",
    reportDescription: "Tuganire ku byabaye. Raporo yawe ishobora kuguma ari ibanga.",
    dropScreenshot: "Shyira foto yawe hano",
    typeInstead: "Andika ubutumwa aho",
    analyzing: "Dusuzuma foto yawe...",
    uploadAnalyze: "Ohereza & Usuzume",
    lowRisk: "Ingaruka Nke",
    lowRiskMsg: "Ubutumwa bwasa ko ari bwiza. Urakora neza!",
    mediumRisk: "Ingaruka Zo Hagati",
    mediumRiskMsg: "Ubutumwa bushobora kugira ingaruka. Dukurinde hamwe.",
    highRisk: "Ingaruka Zikomeye",
    highRiskMsg: "Ubutumwa bushobora kuba bubi. Dukurinde hamwe.",
    analyzingReport: "Gusuzuma...",
    aiReviewing: "AI yacu isuzuma raporo yawe.",
    actionGuidanceOnly: "Inama z'Umutekano",
    actionGuidanceOnlyDesc: "Kurikiza inama z'umutekano hepfo",
    actionAnonymousReport: "Raporo y'Ibanga",
    actionAnonymousReportDesc: "Byanditswe mu mibare y'igihugu",
    actionConnectCounselor: "Ubufasha bw'Umujyanama",
    actionConnectCounselorDesc: "Turagusaba guhuza n'umujyanama",
    actionEmergencyReferral: "Ihutirwa",
    actionEmergencyReferralDesc: "Shaka ubufasha bwihuse",
    noReportData: "Nta raporo yabonetse",
    uploadToStart: "Ohereza foto kugirango utangire.",
    aiReviewedMsg: "AI yacu yasuzumye ubutumwa. Dore ibyo twabonye.",
    mlinziAnalysis: "Isesengura rya AI ya Mlinzi",
    whatFoundInMessage: "Ibyo twabonye mu butumwa",
    wouldLikeHelp: "Ushaka ubufasha bw'umujyanama w'urukingo rw'abana?",
    stayAnonymousOrConnect: "Ushobora kuguma ari ibanga cyangwa uhuze n'umuntu ushobora kukufasha.",
    keepAnonymous: "Guma ari Ibanga",
    connectMeCounselor: "Njyanye ku Mujyanama",
    selectYourDistrict: "Hitamwo akarere kawe",
    contactMethod: "Uburyo bwo Gutumanahana",
    phoneWhatsappNumber: "Nimero ya Telefoni/WhatsApp",
    submitting: "Kohereza...",
    contactEncryptedNote: "Amakuru yawe yo gutumanahana ashyizwe mu banga kandi asangirwa n'umujyanama wawe gusa.",
    imageFileError: "Nyamuneka ohereza ifoto (jpg, png, gif, webp).",
    fileSizeError: "Dosiye igomba kuba munsi ya 5MB.",
    selectScreenshotOrType: "Nyamuneka hitamwo foto cyangwa andika ubutumwa.",
    somethingWrong: "Habaye ikosa. Nyamuneka ongera ugerageze.",
    clickOrDropReplace: "Kanda cyangwa shyira kugirango uhindure",
    orClickBrowse: "cyangwa kanda kugirango usome, cyangwa shyiraho uva ku mbaho (Ctrl+V)",
    maxSize: "jpg, png, gif, webp — ntarengwa 5MB",
    typePasteHarmful: "Andika cyangwa shyiraho ubutumwa bubi hano...",
    typeMessageDirectly: "Ushobora kwandika ubutumwa niba foto idakora.",
    anonymousNoData: "100% ibanga — nta makuru bwite yakusanywe",
    rightThing: "Wakoze neza usaba ubufasha.",
    aiWillAnalyze: "AI yacu izasuzuma ubutumwa kandi itange inama z'ibikurikira byose. Uri mu mutekano hano.",
    counselDashboardSubtitle: "Gucunga raporo no gufasha abana bakeneye ubufasha",
    loadingAnalytics: "Gutegura isesengura...",
    unableToLoad: "Ntibashoboye gutegura isesengura",
    tryRefreshing: "Nyamuneka vugurura urupapuro.",
    evidenceDesc: "Amakuru ashingiye ku bimenyetso ku bayobozi b'inzego",
    escalatedCounselors: "zoherejwe ku bajyanama",
    loadingCase: "Gutegura ikibazo...",
    caseNotFound: "Ikibazo ntigibonetse",
    backToDashboard: "Subira ku Mbonerahamwe",
    caseNumber: "Ikibazo #",
    reportDetails: "Ibisobanuro bya Raporo",
    severity: "Ingaruka",
    recommended: "Birasabwa",
    aiGuidance: "Inama za AI",
    screenshot: "Ifoto y'Skrini",
    followUpNotes: "Inyandiko zo Gukurikirana",
    addNotePlaceholder: "Ongeraho inyandiko kuri iki kibazo...",
    adding: "Kongeraho...",
    addNote: "Ongeraho Inyandiko",
    noNotesYet: "Nta nyandiko zirahari",
    contactInformation: "Amakuru yo Gutumanahana",
    preferredContactLabel: "Uburyo bwo Gutumanahana Bwihitiyemo",
    contactDetails: "Ibisobanuro byo Gutumanahana",
    currentlySafe: "Uri mu mutekano ubu?",
    timeline: "Igihe",
    submitted: "Yoherejwe",
    aiAnalyzed: "Yasuzumwe na AI",
    counselorAssigned: "Umujyanama Wagenwe",
    firstResponse: "Igisubizo cya Mbere",
    underReviewTimeline: "Birimo Gusuzumwa",
    resolvedTimeline: "Byakemutse",
    guidanceOnly: "Inama Gusa",
    anonymousReportLabel: "Raporo y'Ibanga",
    connectToCounselor: "Huza n'Umujyanama",
    emergencyReferralLabel: "Raporo y'Ihutirwa",
    problemSolving: "Ikibazo Dukemura",
    problemDesc: "Abana mu Rwanda no mu Afurika bose barwana n'ingaruka zikomeye kuri interineti, ariko benshi ntabwo bafite uburyo bwiza bwo gutangaza ibikorwa bya nabi. Amategeko ariho ni make kandi asaba amakuru bwite kandi ntashika abana bo mu cyaro.",
    ourPromise: "Isezerano Ryacu",
    promise1: "Ibanga mu Buryo Bwisanzuye",
    promise1Desc: "Nta makuru bwite asabwa kugirango ubone ubufasha",
    promise2: "Inama z'AI",
    promise2Desc: "Isesengura ryihuse n'inama z'umutekano",
    promise3: "Ubufasha bwa Muntu Buhari",
    promise3Desc: "Huza n'abajyanama basimiwe niba bisabwa",
    promise4: "Indimi Nyinshi",
    promise4Desc: "Iboneka mu Kinyarwanda, Igifaransa, n'Icyongereza",
    everyChildProtected: "Umwana wese. Ahantu hose. Arindwa.",
    builtForAfrica: "Mlinzi yubakiwe abana bo mu Rwanda no mu Afurika. Ifunguye kuri bose, ishingiye ku muryango, kandi yateganyijwe gukura kugirango irinde umwana wese kuri interineti.",
    aiPoweredPlatform: "Urubuga rw'AI rwo Kurinda Abana kuri Interineti",
    unicefProject: "Yubakiwe UNICEF Rwanda n'inshuti zazo • Rinda. Wumve. Huza.",
    accessMlinzi: "Koresha Mlinzi mu Buryo Bwawe",
    noSmartphone: "Nta telefoni? Nta interineti? Nta kibazo...",
    webApp: "Porogaramu ya Interineti",
    webAppDesc: "Ohereza amafoto usange isesengura rya AI ryo hato ku ruganda ryose rufite isakaza.",
    smsDesc: "Tuma SMS kuri Mlinzi ukoresheje telefoni isanzwe...",
    whatsappDesc: "Tuma ubutumwa, amafoto, n'amajwi ukoresheje WhatsApp...",
    oneInThree: "1 kuri 3",
    percent80: "80%",
    statChildren: "abana",
    statReport: "ntabwo batangaza ibikorwa bya nabi",
    statOnline: "abana mu Afurika",
    statOnlineDesc: "bagaragarira ingaruka kuri interineti",
    statProtected: "barindwa",
    statProtectedDesc: "intego — kurinda bose",
    protect: "Kurinda",
    listen: "Kwumva",
    support: "Gufasha",
    empower: "Gukomeza",
    protectDesc: "Isesengura rya AI",
    listenDesc: "Gutangaza Ibanga",
    supportDesc: "Guhuza n'Abajyanama",
    empowerDesc: "Amakuru y'Umutekano w'Abana",
    unicefInnovation: "Yubakiwe UNICEF Rwanda",
    videoNotSupported: "Mushakisha wawe ntishyigikira ikintu cyo kwerekana videwo.",
    cookieTitle: "Amakuki & Ibanga",
    cookieMessage: "Dukoresha amakuki ngenderwaho kugirango Mlinzi ikomeze gukora mu mutekano. Ntidukurikirana kandi ntidusangira amakuru yawe. Ubwemera bwawe butugufasha kunoza serivisi zo kurinda abana mu Afurika.",
    cookieAccept: "Emeza Amakuki",
    cookieReject: "Anga",
    privacyTitle: "Politiki y'Ibanga",
    privacySubtitle: "Uburyo dukumira amakuru y'abana n'ubwihishurire bwabo",
    privacyDataTitle: "1. Ibyo Dukusanya",
    privacyDataContent: "Mlinzi ikusanya gusa ibisabwa kugirango ifashe abana:\n\n• Amafoto cyangwa ubutumwa bwatanzwe n'umwana\n• Ibisubizo bya AI (icyiciro, ingaruka, inama)\n• Akarere (gusa niba umwana asaba ubufasha bw'umujyanama)\n• Amakuru yo gutumanahana (gusa niba umwana ahisemo guhuza n'umujyanama)\n\nNTIDUKUSANYA: amazina, amafoto, aderesi ya IP, amakuru ya telefoni, cyangwa amakuru y'umwirondoro uvuye ku raporo z'ibanga.",
    privacyUseTitle: "2. Uburyo Dukoresha Amakuru",
    privacyUseContent: "Amakuru akoreshwa gusa kugirango:\n\n• Isuzumwe ubutumwa bwatanzwe kugirango umwana arinzwe\n• Hatangwe inama ku bana kugirango bakomeze kuba mu mutekano\n• Abana bahuze n'abajyanama basimiwe niba bisabwa\n• Hagenerwe imibare y'igihugu y'ibanga kugirango politiki yo kurinda abana ikorwe\n\nNtidagurisha, ntigabanya, kandi ntidakoresha amakuru mu kwamamaza cyangwa gutondeka.",
    privacyProtectTitle: "3. Uburyo Dukumira Amakuru",
    privacyProtectContent: "• Amakuru yose yashyizwe mu mutekano mu nzira (HTTPS) no mu bikombe\n• Kuboneka kwangiwe abajyanama bemerewe gusa\n• Igenamigambi rigabanya ibikorwa bya nabi n'ibikorwa by'ibyuma\n• Nta tracker y'ibanga cyangwa y'isesengura\n• Code ifunguye — ishobora gusuzumwa na buri wese",
    privacyChildrenTitle: "4. Ibanga ry'Abana",
    privacyChildrenContent: "Mlinzi yubakiwe cyane kugirango abana bayikoreshe. Dukurikiza amategeko meza y'urukingo rw'amakuru y'abana:\n\n• Ibanga mu buryo bwisanzuye — nta makuru bwite asabwa kugirango ubone ubufasha\n• Nta konti ikenewe kugirango umuntu atangaze ikibazo\n• Kwemera kw'ababyeyi ntikenewe kugirango umuntu atangaze ikibazo cy'ibanga\n• Kuboneka k'umujyanama bishingiye ku kwemera k'umwana\n• Dukurikiza amategeko y'ibanga y'u Rwanda n'ibyerekezo vya UNICEF ku buhumyunzere bw'abana kuri interineti",
    privacyRetentionTitle: "5. Kubika Amakuru",
    privacyRetentionContent: "• Raporo z'ibanga: zibikwa kugeza imyaka 2 kugirango imibare y'igihugu ikorwe\n• Ibyiciro vy'abajyanama: bibikwa kugeza umwaka 1 nyuma y'ikemurwa\n• Amakuru ya SMS/WhatsApp: asibwa nyuma y'iminsi 90 atakoze\n• Amakuru yo gutumanahana: asibwa vuba nyuma y'iyungana na muganga\n• Abana bashobora gusaba ko amakuru yabo asibwa igihe cyose",
    privacyDeleteTitle: "6. Gusiba Amakuru",
    privacyDeleteContent: "Abana (cyangwa ababyezi babo) bashobora gusaba gusiba amakuru yabo yose igihe cyose mu buryo bukurikira:\n\n• Ohereza imeri kuri privacy@mlinzi.org\n• Ohereza ubutumwa kuri Mlinzi ukoresheje 'SIBA AMAKURU YANJYE'\n• Saba umujyanama wawe ko yohereza icyifuzo cyo gusiba amakuru\n\nAmakuru yose azasibwa burundu mu masaha 72 nyuma yo kwemezwa.",
    privacyRightsTitle: "7. Uburenganzira Bwawe",
    privacyPrivacyRightsContent: "Umwana wese afite uburenganzira bwo:\n\n• Gutangaza ibanga nta makuru bwite atanga\n• Kumenya amakuru yakusanywe yerekeranye na we\n• Gusaba ko amakuru adatunganye atandurwa\n• Gusaba ko amakuru yose asibwa\n• Guhindura kwemera kw'iyungana na muganga igihe cyose\n• Gutanga ikirego niba ubwihishurire bwe bukoreshejwe nabi",
    privacyContactTitle: "8. Twandikire",
    privacyContactContent: "Kugirango ubaze ibibazo by'ibanga, gusaba amakuru, cyangwa gutanga ikirego:\n\nImeri: privacy@mlinzi.org\nTelefoni: +250 788 123 456\nAderesi: UNICEF Rwanda, KG 7 Ave, Kigali\n\nUmuyobozi w'Urukingo rw'Amakuru: dpo@mlinzi.org",
    privacyLastUpdated: "Ivuguruwe ku wa: Kanama 2026 • Urubuga rw'AI rwo Kurinda Abana kuri Interineti",
    forgotPasswordTitle: "Wibagiwe Ijambo ry'Ibanga",
    forgotPasswordDesc: "Injiza imeri yawe kandi tuzakohereza ikiyungo cyo guhindura",
    backToLogin: "Subira ku Kwinjira",
    checkEmailTitle: "Suzuma Imeri Yawe",
    checkEmailDesc: "Twohereje ikiyungo cyo guhindura ijambo ry'ibanga kuri",
    noEmailCheck: "Ntiyabonyeho? Suzuma spam cyangwa ongera ugerageze.",
    tryDifferentEmail: "Koresha imeri yindi",
    resetYourPassword: "Hindura Ijambo ry'Ibanga",
    enterEmailBelow: "Injiza aderesi ya imeri yawe yanditswe",
    emailAddress: "Aderesi ya Imeri",
    sending: "Kohereza...",
    sendResetLink: "Ohereza Ikiyungo",
    resetPasswordTitle: "Shyira Ijambo ry'Ibanga Rishya",
    resetPasswordDesc: "Hitamwo ijambo ry'ibanga rikomeye kuri konti yawe",
    invalidResetLink: "Ikiyungo Kibi",
    invalidResetLinkDesc: "Iki kiyungo cyo guhindura ijambo ry'ibanga nticyo cyangwa cyararangiye.",
    requestNewLink: "Saba Ikiyungo Gishya",
    setNewPassword: "Shyira Ijambo ry'Ibanga Rishya",
    mustBe8Chars: "Bigomba kuba byibura inyuguti 8",
    newPassword: "Ijambo ry'Ibanga Rishya",
    confirmPassword: "Emeza Ijambo ry'Ibanga",
    passwordsNoMatch: "Amagambo y'ibanga ntahura",
    passwordTooShort: "Ijambo ry'ibanga rigomba kuba rifite byibura inyuguti 8",
    resetting: "Guhindura...",
    passwordResetSuccess: "Guhindura Ijambo ry'Ibanga Byagenze Neza",
    passwordResetSuccessDesc: "Ijambo ry'ibanga ryawe ryahinduwe. Ushobora noneho kwinjira ukoresheje ijambo ry'ibanga rishya.",
    goToLogin: "Jya ku Kwinjira",
    enterPhoneNumber: "Injiza Nimero ya Telefoni Yawe",
    otpWillBeSent: "Tuzakohereza kodi yo kwemeza na SMS",
    phoneLabel: "Nimero ya Telefoni",
    sendCode: "Ohereza Kodi",
    enterCode: "Injiza Kodi yo Kwemeza",
    codeSentTo: "Kodi yoherejwe kuri",
    verifying: "Kwemeza...",
    verifyCode: "Emeza Kodi",
    resendIn: "Ongera uohereze kodi mu",
    resendCode: "Ongera Uohereze Kodi",
    phoneVerified: "Telefoni Yemejwe",
    phoneVerifiedDesc: "Telefoni yawe yemejwe. Ushobora noneho guhindura ijambo ry'ibanga.",
    chooseHowToReset: "Ushaka Guhindura Ute?",
    chooseChannelDesc: "Hitamwo aho ushaka kwakira kodi yo kwemeza",
    smsOtp: "Kodi ya SMS",
    smsOtpDesc: "Akira kodi y'imibare 6 na SMS",
    emailOtp: "Kodi ya Imeri",
    emailOtpDesc: "Akira kodi y'imibare 6 na imeri",
    enterEmailAddress: "Injiza Aderesi ya Imeri Yawe",
    verificationVerified: "Yemejwe Neza",
  },
};

const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "rw", label: "Kinyarwanda" },
];

const LOCALE_MAP = {
  en: "en-US",
  fr: "fr-FR",
  rw: "rw-RW",
};

export function AccessibilityProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("mlinzi_lang") || "en";
  });
  const [highContrast, setHighContrast] = useState(() => {
    return localStorage.getItem("mlinzi_contrast") === "true";
  });
  const [largeText, setLargeText] = useState(() => {
    return localStorage.getItem("mlinzi_largetext") === "true";
  });

  useEffect(() => {
    localStorage.setItem("mlinzi_lang", language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem("mlinzi_contrast", highContrast);
    document.documentElement.classList.toggle("high-contrast", highContrast);
  }, [highContrast]);

  useEffect(() => {
    localStorage.setItem("mlinzi_largetext", largeText);
    document.documentElement.classList.toggle("large-text", largeText);
  }, [largeText]);

  function t(key) {
    return translations[language]?.[key] || translations.en[key] || key;
  }

  function formatDate(date, options = {}) {
    const locale = LOCALE_MAP[language] || "en-US";
    return new Date(date).toLocaleDateString(locale, options);
  }

  function formatDateTime(date, options = {}) {
    const locale = LOCALE_MAP[language] || "en-US";
    return new Date(date).toLocaleString(locale, options);
  }

  return (
    <AccessibilityContext.Provider
      value={{
        language,
        setLanguage,
        highContrast,
        setHighContrast,
        largeText,
        setLargeText,
        t,
        formatDate,
        formatDateTime,
        languages: LANGUAGES,
      }}
    >
      {children}
    </AccessibilityContext.Provider>
  );
}

export function useAccessibility() {
  const context = useContext(AccessibilityContext);
  if (!context) {
    throw new Error("useAccessibility must be used within AccessibilityProvider");
  }
  return context;
}
